SET NAMES utf8;

UPDATE `transports` SET `name` = 'Vaisseau de combat de la Horde' WHERE entry = 195276;
UPDATE `transports` SET `name` = 'Vaisseau de combat de l\'Alliance' WHERE entry = 195121;
UPDATE `transports` SET `name` = 'La citadelle de Glace (Alliance)' WHERE entry = 201811;
UPDATE `transports` SET `name` = 'La citadelle de Glace (Horde)' WHERE entry = 201812;
UPDATE `transports` SET `name` = 'Le Brise-ciel' WHERE entry = 201598;
UPDATE `transports` SET `name` = 'Le Marteau d\'Orgrim' WHERE entry = 201599;
UPDATE `transports` SET `name` = 'Raid ICC, Le Marteau d\'Orgrim' WHERE entry = 201581;
UPDATE `transports` SET `name` = 'Raid ICC, Le Brise-ciel' WHERE entry = 201580;
UPDATE `transports` SET `name` = 'Zeppelin, Horde (Raid ICC)' WHERE entry = 201834;
UPDATE `transports` SET `name` = 'Orgrimmar et Les Pitons du Tonnerre' WHERE entry = 190549;
UPDATE `transports` SET `name` = 'Le Marteau d\'Orgrim' WHERE entry = 192241;
UPDATE `transports` SET `name` = 'Piste d\'atterrissage de Spumelevier' WHERE entry = 192242;
UPDATE `transports` SET `name` = 'Bateau Pirate' WHERE entry = 187038;
UPDATE `transports` SET `name` = 'Orgrimmar et Fossoyeuse' WHERE entry = 164871;
UPDATE `transports` SET `name` = 'Campement Grom\'Gol et Fossoyeuse' WHERE entry = 176495;
UPDATE `transports` SET `name` = 'Port de Menethil et Auberdine' WHERE entry = 176310;
UPDATE `transports` SET `name` = 'Teldrassil et Auberdine' WHERE entry = 176244;
UPDATE `transports` SET `name` = 'Port de Menethil et L\'île de Theramore' WHERE entry = 176231;
UPDATE `transports` SET `name` = 'Campement Grom\'Gol et Orgrimmar' WHERE entry = 175080;
UPDATE `transports` SET `name` = 'Cabestan et Baie-du-butin' WHERE entry = 20808;
UPDATE `transports` SET `name` = 'La côte oubliée et l\'île de sardor' WHERE entry = 177233;
UPDATE `transports` SET `name` = 'île de brume-azur et Auberdine' WHERE entry = 181646;
UPDATE `transports` SET `name` = 'Valgarde et Port de Menethil' WHERE entry = 181688;
UPDATE `transports` SET `name` = 'Fossoyeuse et Accostage de la Vengeance' WHERE entry = 181689;
UPDATE `transports` SET `name` = 'Orgrimmar et Bastion Chanteguerre' WHERE entry = 186238;
UPDATE `transports` SET `name` = 'Porte d\'Hurlevent et Donjon de la bravoure, Toundra Boréenne ("Le Kraken") ' WHERE entry = 190536;
