SET NAMES utf8;

UPDATE `db_script_string` SET `content_loc2` = 'Entrez dans l\'arène de sang, $N. Le combat va commencer !' WHERE `entry` = 2000000001;
UPDATE `db_script_string` SET `content_loc2` = 'Le combat est sur le point de commencer !' WHERE `entry` = 2000000002;
UPDATE `db_script_string` SET `content_loc2` = '$N contre le féroce Sabot-fourchu Brisorteil !' WHERE `entry` = 2000000003;
UPDATE `db_script_string` SET `content_loc2` = 'Je m’y mets immédiatement, $N.' WHERE `entry` = 2000000004;
UPDATE `db_script_string` SET `content_loc2` = 'Bon... où sont passés mon fil et mon aiguille. Ah ! Les voilà...' WHERE `entry` = 2000000005;
UPDATE `db_script_string` SET `content_loc2` = '%s commence à lancer un sort pendant que vous lui retirez la cape.' WHERE `entry` = 2000000006;
UPDATE `db_script_string` SET `content_loc2` = 'Partez maintenant, $N. Trouvez Volcor... Et n\'oubliez pas, la magie qui vous protège s\'annulera si vous devez interagir avec quelqu\'un, sauf si ce n\'est pour discuter.' WHERE `entry` = 2000000007;
UPDATE `db_script_string` SET `content_loc2` = 'Hâtez-vous, $N. Traversez le portail !' WHERE `entry` = 2000000008;
UPDATE `db_script_string` SET `content_loc2` = 'Très bien, allons y.' WHERE `entry` = 2000000012;
UPDATE `db_script_string` SET `content_loc2` = 'Oh non ! Ils sont ici !' WHERE `entry` = 2000000013;
UPDATE `db_script_string` SET `content_loc2` = 'Oh, bonjour Griffe-sinistre.' WHERE `entry` = 2000000014;
UPDATE `db_script_string` SET `content_loc2` = 'Bien, $N. Maintenant je peux rentrer tout seul à Auberdine. Aller voir Terenthis, il vous attend. Merci encore de votre aide.' WHERE `entry` = 2000000015;
UPDATE `db_script_string` SET `content_loc2` = 'D\'accord, merci pour l\'aide l\'ami et bonne chance.' WHERE `entry` = 2000000016;
UPDATE `db_script_string` SET `content_loc2` = 'Ok, c\'est parti !' WHERE `entry` = 2000000017;
UPDATE `db_script_string` SET `content_loc2` = 'Je peux faire le reste du chemin tout seul. $N. MERCI !' WHERE `entry` = 2000000018;
UPDATE `db_script_string` SET `content_loc2` = 'Soyez patient $N. Le flambeau est bientôt consummé.' WHERE `entry` = 2000000019;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est intéressant...' WHERE `entry` = 2000000020;
UPDATE `db_script_string` SET `content_loc2` = 'Je dois consulter Noram et Horatio.' WHERE `entry` = 2000000021;
UPDATE `db_script_string` SET `content_loc2` = 'Regardez : Les séides de Terokk viennent ici !' WHERE `entry` = 2000000022;
UPDATE `db_script_string` SET `content_loc2` = 'Par ici ! D\'autres arrivent !' WHERE `entry` = 2000000023;
UPDATE `db_script_string` SET `content_loc2` = 'Et même plus !' WHERE `entry` = 2000000024;
UPDATE `db_script_string` SET `content_loc2` = 'Un avatar de Terokk ! Aux armes !' WHERE `entry` = 2000000025;
UPDATE `db_script_string` SET `content_loc2` = 'Oups !' WHERE `entry` = 2000000026;
UPDATE `db_script_string` SET `content_loc2` = '%s désigne la cruche d\'eau se trouvant sur le rebord du puits.' WHERE `entry` = 2000000027;
UPDATE `db_script_string` SET `content_loc2` = 'Le peuple de la marche de l\'Ouest salut $N, $gun brave et vaillant défenseur:une brave et vaillante défenseuse; de la liberté.' WHERE `entry` = 2000000028;
UPDATE `db_script_string` SET `content_loc2` = 'Suivez-moi, $N. Je vais bientôt commencer l\'invocation...' WHERE `entry` = 2000000029;
UPDATE `db_script_string` SET `content_loc2` = 'Cela a du sens !' WHERE `entry` = 2000000030;
UPDATE `db_script_string` SET `content_loc2` = 'Votre corps est à moi ! Nos destins sont pour toujours entrelacés !' WHERE `entry` = 2000000031;
UPDATE `db_script_string` SET `content_loc2` = 'Tenez vous bien $N, pour le démon qui se trouve dans l\'orbe c\'est une bête gangrenée.' WHERE `entry` = 2000000032;
UPDATE `db_script_string` SET `content_loc2` = 'Restez en mouvement !' WHERE `entry` = 2000000033;
UPDATE `db_script_string` SET `content_loc2` = 'Venez, $N. Le seigneur Hurlorage attend.' WHERE `entry` = 2000000034;
UPDATE `db_script_string` SET `content_loc2` = 'Guerriers Gueule-de-Dragon, rassemblement ! Un de vous a atteint le rang de Seigneur Suprême ! Baissez la tête et à genoux ! Montrez votre respect et votre allégeance envers le Seigneur Suprême, $N !' WHERE `entry` = 2000000035;
UPDATE `db_script_string` SET `content_loc2` = 'Le seigneur Illidan sera la sous peu.' WHERE `entry` = 2000000036;
UPDATE `db_script_string` SET `content_loc2` = 'Que tous salue le Seigneur Illidan !' WHERE `entry` = 2000000037;
UPDATE `db_script_string` SET `content_loc2` = 'Seigneur Illidan, voici le Gueule-de-Dragon dont nous vous avons parlé. Il nous guidera vers la victoire !' WHERE `entry` = 2000000038;
UPDATE `db_script_string` SET `content_loc2` = 'Mais... Mon seigneur, je ne comprends pas. $N... Ce sont les orcs qui ont...' WHERE `entry` = 2000000039;
UPDATE `db_script_string` SET `content_loc2` = 'Ce sera fait, mon seigneur.' WHERE `entry` = 2000000040;
UPDATE `db_script_string` SET `content_loc2` = 'Vous pensez pouvoir vous moquer de Mor\'ghor, hein ? Avant que vous ne soyez envoyés vers le seigneur Illidan, vous allez connaître des souffrances que vous ne soupçonniez même pas. Je vais y prendre du plaisir comme s\'il s\'agissait de ma propre vengeance.' WHERE `entry` = 2000000041;
UPDATE `db_script_string` SET `content_loc2` = 'Jusqu\'à notre prochaine rencontre !' WHERE `entry` = 2000000042;
UPDATE `db_script_string` SET `content_loc2` = 'commence un sort d\'invocation...' WHERE `entry` = 2000000043;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est fait...' WHERE `entry` = 2000000044;
UPDATE `db_script_string` SET `content_loc2` = 'Un thé brûlant, il n\'y a rien de tel pour bien commencer la journée lorsque l\'air est frais à Dun Morogh !' WHERE `entry` = 2000000045;
UPDATE `db_script_string` SET `content_loc2` = 'Oooooo chaud chaud chaud ! Si cela ne vous revigore pas, je ne sais pas ce qui le fera.' WHERE `entry` = 2000000046;
UPDATE `db_script_string` SET `content_loc2` = 'Croa ! Non ! Cela ne peut pas... croa... être ! Vous m\'avez trompé avec... croa...  vos supercheries ! Croa !' WHERE `entry` = 2000000047;
UPDATE `db_script_string` SET `content_loc2` = 'Laissez-moi maintenant placer cette terre rare dans mon terreau...' WHERE `entry` = 2000000048;
UPDATE `db_script_string` SET `content_loc2` = 'Merci encore, $N. Cette terre rare sera très utile dans mes expériences.' WHERE `entry` = 2000000049;
UPDATE `db_script_string` SET `content_loc2` = 'Une tâche assez simple que de briser cette pierre d\'âme !' WHERE `entry` = 2000000050;
UPDATE `db_script_string` SET `content_loc2` = 'La gemme d\'âme luminescente explose en s\'ouvrant !' WHERE `entry` = 2000000051;
UPDATE `db_script_string` SET `content_loc2` = 'Finalement, nous devons en finir avec Athrikus Narassin. Dites-moi, esprit, où pourrions-nous trouver les autres pierres d\'âmes, afin de briser cette magie ?' WHERE `entry` = 2000000052;
UPDATE `db_script_string` SET `content_loc2` = 'Sarath disparaît dans la brume...' WHERE `entry` = 2000000053;
UPDATE `db_script_string` SET `content_loc2` = 'Combien de fantassins dois-je renvoyer dans un sac à leur mère et à leur père avant que vous ne compreniez qu\'il ne sert à rien de foncer tête la première contre une patrouille de la Légion ?  Et ne faites pas comme si vous sachiez de quoi je parle !' WHERE `entry` = 2000000055;
UPDATE `db_script_string` SET `content_loc2` = 'Holà, Belm ! Sers-moi une chope de Tonneblonde et mets-en une aussi pour $gmon cher ami:ma chère amie; $N.' WHERE `entry` = 2000000056;
UPDATE `db_script_string` SET `content_loc2` = 'Esprit de l\'eau, je chante vos louanges, et je vous prie de nous accorder une faveur. Vous avez entendu $N , et je suis convaincu que son coeur est noble. S’il vous plaît, allez-vous nous aider ?' WHERE `entry` = 2000000057;
UPDATE `db_script_string` SET `content_loc2` = 'Merci grand esprit ! Merci !' WHERE `entry` = 2000000058;
UPDATE `db_script_string` SET `content_loc2` = 'Vous êtes renvoyé, $N' WHERE `entry` = 2000000059;
UPDATE `db_script_string` SET `content_loc2` = 'Par les étoiles ! Un esprit a été invoqué !' WHERE `entry` = 2000000060;
UPDATE `db_script_string` SET `content_loc2` = 'C’est un mystère du passé, pour sûr ! Mais aussi une clé pour notre avenir !' WHERE `entry` = 2000000061;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est la fin de la menace ! $N nous a tous sauvés !' WHERE `entry` = 2000000062;
UPDATE `db_script_string` SET `content_loc2` = 'Suivez-moi, bien $C. Je peux vous faire votre carapaçon plus vite que je n\'abattrais un solide Nain !' WHERE `entry` = 2000000063;
UPDATE `db_script_string` SET `content_loc2` = 'Eh bien, cela devrait convenir. Venez maintenant, retour à la boutique pour terminer notre affaire !' WHERE `entry` = 2000000064;
UPDATE `db_script_string` SET `content_loc2` = 'Nous ne tolérerons pas la présence des serviteurs des démons dans notre contrée !' WHERE `entry` = 2000000065;
UPDATE `db_script_string` SET `content_loc2` = 'Que la paix et la patience soient avec vous, $N. Restez toujours fort.' WHERE `entry` = 2000000066;
UPDATE `db_script_string` SET `content_loc2` = 'Que fait un intrus comme vous dans le royaume d\'Ysera ? Je vous dis de nous laisser ! Les gens de votre espèce ne sont pas les bienvenus ici !' WHERE `entry` = 2000000067;
UPDATE `db_script_string` SET `content_loc2` = 'Vous... vous n\'êtes pas l\'un d\'entre eux ! Mettons nous à l\'abris avant qu\'ils nous trouvent ! Vite !' WHERE `entry` = 2000000068;
UPDATE `db_script_string` SET `content_loc2` = 'Ils me suivent, $R ! Rapidement, dites-moi pourquoi vous êtes ici avant que nous soyons découverts ! S\'ils nous attrapent, cela signifiera ma mort et la vôtre !' WHERE `entry` = 2000000069;
UPDATE `db_script_string` SET `content_loc2` = 'Cela aurait pris des années pour trouver le Livre du Corbeau sans vous, jeune Crécerelle. Retournez vers votre terre Nagrand avec notre gratitude.' WHERE `entry` = 2000000070;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est ça ! C\'est vraiment ça -- Le Livre du Corbeau !' WHERE `entry` = 2000000071;
UPDATE `db_script_string` SET `content_loc2` = 'Tout est ici... la façon dont les adeptes du corbeau ont capturés et soumis les esprits rivaux, piégés à jamais dans les statues de pierre ! La tablette mentionne même le nom du Dieu Corbeau - Anzu. Je pensais qu\'il était perdu pour l\'histoire !' WHERE `entry` = 2000000072;
UPDATE `db_script_string` SET `content_loc2` = 'Il y a quelque chose d\'autre ici. Après la description d\'une bataille sanglante et de la chute du Dieu Corbeau, il y a une prophétie. Anzu va hanter les rêves de ses ennemis, et les tourmenter pour revenir dans ce monde...' WHERE `entry` = 2000000073;
UPDATE `db_script_string` SET `content_loc2` = 'La tablette nous apporte la confirmation dont nous avons besoin, tout comme je le pensais. Maintenant, nous devons utiliser ces informations pour tirer et défaire Anzu avant qu\'il ne fasse d\'avantage de dégâts au Rêve d\'Emeraude !' WHERE `entry` = 2000000074;
UPDATE `db_script_string` SET `content_loc2` = 'Depuis que les Crécerelles ont eu un tel succès en retrouvant les pierres de corbeau, la Gardienne Elaira en a entraîné un autre pour retransmettre ma voix à grande distance. Il peut nous aider à communiquer avec les esprits d\'oiseaux qui ont été révélés par la tablette sur laquelle nous enquêtons !' WHERE `entry` = 2000000075;
UPDATE `db_script_string` SET `content_loc2` = 'Écoutez, habitants de Tanaris ! Que l\'on sache que $N est un membre exalté de l\'ordre du Mithril. Un forgeron d\'honneur, dévoué et d\'une infinie patience. Hourra pour $N !' WHERE `entry` = 2000000076;
UPDATE `db_script_string` SET `content_loc2` = 'Ah, ça fait du bien là où ça passe ! Je crois que je vais m\'en verser deux autres... Vous pouvez surveiller ces tonneaux à ma place, $N ?' WHERE `entry` = 2000000077;
UPDATE `db_script_string` SET `content_loc2` = 'Comment se passe la surveillance des tonneaux ?' WHERE `entry` = 2000000078;
UPDATE `db_script_string` SET `content_loc2` = 'Bien, je reprends mon service. Mais cette petite pause était bien agréable et c’est toujours un plaisir de boire de la Tonneblonde !' WHERE `entry` = 2000000079;
UPDATE `db_script_string` SET `content_loc2` = 'Ça ne devrait pas être long...' WHERE `entry` = 2000000080;
UPDATE `db_script_string` SET `content_loc2` = 'Votre potion d\'invisibilité est prête, $N.' WHERE `entry` = 2000000081;
UPDATE `db_script_string` SET `content_loc2` = 'Je... je... me... sens... pas... bien...' WHERE `entry` = 2000000082;
UPDATE `db_script_string` SET `content_loc2` = 'Mon esprit... ma chair... je me décompose...!' WHERE `entry` = 2000000083;
UPDATE `db_script_string` SET `content_loc2` = 'Je lève mon verre et j\'espère me débarrasser des gens comme vous ! Santé ! Vous n\'êtes pas une mauvaise canaille, $N !' WHERE `entry` = 2000000084;
UPDATE `db_script_string` SET `content_loc2` = 'Prenez une Bougie de Signal de cette caisse, $N.' WHERE `entry` = 2000000085;
UPDATE `db_script_string` SET `content_loc2` = '%s enlève les graines des Fruits Luminescents...' WHERE `entry` = 2000000086;
UPDATE `db_script_string` SET `content_loc2` = 'Voyons comment ces graines poussent dans mon terreau...' WHERE `entry` = 2000000087;
UPDATE `db_script_string` SET `content_loc2` = '%s plante les graines de fruits.' WHERE `entry` = 2000000088;
UPDATE `db_script_string` SET `content_loc2` = 'Des tourbelins sortent du sol !' WHERE `entry` = 2000000089;
UPDATE `db_script_string` SET `content_loc2` = '%s étudie le parchemin du Tome du Crépuscule...' WHERE `entry` = 2000000090;
UPDATE `db_script_string` SET `content_loc2` = '%s est frappé par la magie qui vient d\'être libérée !' WHERE `entry` = 2000000091;
UPDATE `db_script_string` SET `content_loc2` = 'Hmm...' WHERE `entry` = 2000000092;
UPDATE `db_script_string` SET `content_loc2` = '%s se précipite vers son bac à plantes.' WHERE `entry` = 2000000093;
UPDATE `db_script_string` SET `content_loc2` = 'J\'espère que cette pousse prendra racine...' WHERE `entry` = 2000000094;
UPDATE `db_script_string` SET `content_loc2` = '%s commence à psalmodier en mélangeant les pierres de puits et les pommes de pin devant le Feu Tribal.' WHERE `entry` = 2000000095;
UPDATE `db_script_string` SET `content_loc2` = 'L\'Eau des Prophètes est prête à être consommée, $N.' WHERE `entry` = 2000000096;
UPDATE `db_script_string` SET `content_loc2` = '%s inspecte les carapaces de Gueules d\'acier...' WHERE `entry` = 2000000097;
UPDATE `db_script_string` SET `content_loc2` = 'Hm...' WHERE `entry` = 2000000098;
UPDATE `db_script_string` SET `content_loc2` = 'Étrange. Très étrange...' WHERE `entry` = 2000000099;
UPDATE `db_script_string` SET `content_loc2` = '$N. Ces carapaces vont m\'en apprendre davantage, mais j\'ai peur qu\'elles n\'apportent encore plus de questions...' WHERE `entry` = 2000000100;
UPDATE `db_script_string` SET `content_loc2` = 'Bien, voyons voir ça...' WHERE `entry` = 2000000101;
UPDATE `db_script_string` SET `content_loc2` = 'Oh, malédiction...' WHERE `entry` = 2000000102;
UPDATE `db_script_string` SET `content_loc2` = 'Ok, c\'est parti !' WHERE `entry` = 2000000103;
UPDATE `db_script_string` SET `content_loc2` = '... oops.' WHERE `entry` = 2000000104;
UPDATE `db_script_string` SET `content_loc2` = 'Les Esprits des Serres-Rocheuses sont toujours déchaînés, $N.' WHERE `entry` = 2000000105;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai bien peur que nous les soulagions jamais...' WHERE `entry` = 2000000106;
UPDATE `db_script_string` SET `content_loc2` = 'Pauvre Dorius. Si jamais je mets la main sur ces Sombrefer, donc aidez moi...' WHERE `entry` = 2000005000;
UPDATE `db_script_string` SET `content_loc2` = 'Opus veut plus d\'Or de Cuergo... avec le ver.' WHERE `entry` = 2000005001;
UPDATE `db_script_string` SET `content_loc2` = 'Bijou perdu ! SQUAWK ! *Tousse*' WHERE `entry` = 2000005002;
UPDATE `db_script_string` SET `content_loc2` = 'Kibler fait l\'objet d\'une enquête du G.E.T.A.' WHERE `entry` = 2000005003;
UPDATE `db_script_string` SET `content_loc2` = 'Bijou sait où les trésors sont cachés.' WHERE `entry` = 2000005004;
UPDATE `db_script_string` SET `content_loc2` = 'Les dragons controllent les orcs !? SQUAWK !' WHERE `entry` = 2000005005;
UPDATE `db_script_string` SET `content_loc2` = 'Ils vont tous au Pic mais ne reviennent jamais... tout comme Bijou.' WHERE `entry` = 2000005006;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez à Kibler a propos du trésor ! SQUAWK !' WHERE `entry` = 2000005007;
UPDATE `db_script_string` SET `content_loc2` = 'SQUAWK !! *tousse* *tousse* Je dois arrêté de fumer !' WHERE `entry` = 2000005008;
UPDATE `db_script_string` SET `content_loc2` = 'Bien jouer, soldats ! Repos !' WHERE `entry` = 2000005009;
UPDATE `db_script_string` SET `content_loc2` = 'Zug zug ! Content de pouvoir aider !' WHERE `entry` = 2000005010;
UPDATE `db_script_string` SET `content_loc2` = 'Oui maman tout de suite !' WHERE `entry` = 2000005011;
UPDATE `db_script_string` SET `content_loc2` = 'De mystérieuses empreintes de sabots, un bouclier brûlé, des insignes égarés… comment donner un sens à tout ça ?' WHERE `entry` = 2000005012;
UPDATE `db_script_string` SET `content_loc2` = 'Je pense que Drazzit va avoir besoin de chance pour trouver quelqu\'un pour tuer ce rapace. Je veux dire, il a déjà augmenté deux fois le prix de la récompense...' WHERE `entry` = 2000005013;
UPDATE `db_script_string` SET `content_loc2` = 'Mais c\'est le seul à la taille de Brogg ! Gobelins construire trop petit !' WHERE `entry` = 2000005014;
UPDATE `db_script_string` SET `content_loc2` = 'Brogg, on en a déjà parlé. Tu ne peux pas rester dans ce bâtiment. Bien sûr, il est à ta taille, mais il n\'y a plus de place pour rien d\'autre !' WHERE `entry` = 2000005015;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, on a dit que tu pouvais rester, mais ce bâtiment est notre quartier général. C\'est là qu\'on garde tous nos manuels et tous nos plans !' WHERE `entry` = 2000005016;
UPDATE `db_script_string` SET `content_loc2` = 'Question de point de vue. Je pense que quelqu\'un a construit les ogres trop grands. Bon, je ne vais pas te convaincre de bouger, mais ne t\'imagine pas que c\'est définitif !' WHERE `entry` = 2000005017;
UPDATE `db_script_string` SET `content_loc2` = 'Ah, ça doît être lui maintenant... non ?' WHERE `entry` = 2000005018;
UPDATE `db_script_string` SET `content_loc2` = 'Vous devriez reculer. C\'est salissant, de vider des poissons.' WHERE `entry` = 2000005019;
UPDATE `db_script_string` SET `content_loc2` = 'C’est bon de voir que vous êtes fier de défendre Theramore, mon ami.' WHERE `entry` = 2000005020;
UPDATE `db_script_string` SET `content_loc2` = 'Allons à l’auberge lorsque vous ne serez plus de service. Je vous payerai un verre et nous pourrons nous remémorer le bon vieux temps.' WHERE `entry` = 2000005021;
UPDATE `db_script_string` SET `content_loc2` = 'Voudriez-vous voir revenir cette époque ? Parce que j’ai des amis qui savent peut-être comment faire…' WHERE `entry` = 2000005022;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai acquéri moi même tous les objets que j\'ai à vendre. Je peux vous garantir personnellement leurs authenticités.' WHERE `entry` = 2000005023;
UPDATE `db_script_string` SET `content_loc2` = 'Il s\'échappe !' WHERE `entry` = 2000005024;
UPDATE `db_script_string` SET `content_loc2` = 'Prix ! Venez récuperer vos prix ici ! Venez par ici et faites le tour de la Foire de Sombrelune pour des prix de grandes valeurs !' WHERE `entry` = 2000005025;
UPDATE `db_script_string` SET `content_loc2` = 'Venez parler avec moi, et une fois que ce sera fait tout ce qui a été nuageux deviendra clair comme du cristal.' WHERE `entry` = 2000005026;
UPDATE `db_script_string` SET `content_loc2` = 'Le Roi Liche constitue ces forces. Il est impératif que notre calendrier soutienne ses plans.' WHERE `entry` = 2000005027;
UPDATE `db_script_string` SET `content_loc2` = 'Demain, nous allons commencer la formation de nos dragons, alors n\'oubliez pas vos jouets à mâcher.' WHERE `entry` = 2000005028;
UPDATE `db_script_string` SET `content_loc2` = 'Notre plus ancienne prise de dragons est toujours loin de la maturité, mais avec de la patience et du sérieux, nous sommes sûrs que les dragons seront bientôt prêts.' WHERE `entry` = 2000005029;
UPDATE `db_script_string` SET `content_loc2` = 'Si vous attendez pour venir me voir, il n\'y aura peut être plus rien !' WHERE `entry` = 2000005030;
UPDATE `db_script_string` SET `content_loc2` = 'Je viens du monde souterrain... là où les femmes ont la peste et les hommes tombent en morceaux.' WHERE `entry` = 2000005031;
UPDATE `db_script_string` SET `content_loc2` = '... Et la le Tauren dit, "13 Pouces !"' WHERE `entry` = 2000005032;
UPDATE `db_script_string` SET `content_loc2` = 'Venez ! Venez tous ! Bienvenue à la foire de Sombrelune ! Vous rêvez d\'aventure ? Vous cherchez des trésors exotiques et mystérieux ? N\'allez pas plus loin ! Vous, mon ami, vous êtes ici au bon endroit ! Plongez droit vers la foire et prenez part à tout ce qu\'on a à vous offrir ! Nous serons à cet endroit toute la semaine, donc assurez-vous de prévenir vos amis et vos proches !' WHERE `entry` = 2000005033;
UPDATE `db_script_string` SET `content_loc2` = 'Bienvenue à toutes et à tous à la foire de Sombrelune, le plus grand événement de tous les mondes ! Nous avons de tout... des plats délicieux, des boissons fortes, des objets exotiques, un diseur de bonne aventure, des prix incroyables et de l\'excitation sans fin ! N\'oubliez pas d\'aller voir Gelvas Grasseporte pendant que vous faîtes un tour dans la foire de Sombrelune pour échanger vos billets ! Il vous faut au minimum cinq tickets et vous êtes sûr de trouver le plus merveilleux des prix de toute l\'Outreterre. Tout le monde est gagnant.' WHERE `entry` = 2000005034;
UPDATE `db_script_string` SET `content_loc2` = 'Il s\'échappe !' WHERE `entry` = 2000005035;
UPDATE `db_script_string` SET `content_loc2` = 'S\'il vous plaît ! Je dois me nourrir de quelque chose... Un cristal de mana... un éclat... n\'importe quoi ! La douleur est insupportable !' WHERE `entry` = 2000005036;
UPDATE `db_script_string` SET `content_loc2` = 'Je dois juste aller chasser cette bête avariée maintenant qu\'il y a une prime sur sa tête.' WHERE `entry` = 2000005037;
UPDATE `db_script_string` SET `content_loc2` = 'Dîtes nous ! Qu\'est ce que votre chef nous cache ?' WHERE `entry` = 2000005038;
UPDATE `db_script_string` SET `content_loc2` = 'Le vent nous parle des mouvements de nos ennemis, Ashyen. Les Nagas vont attaquer de nouveau.' WHERE `entry` = 2000005039;
UPDATE `db_script_string` SET `content_loc2` = 'Très bien. Quand cette décision sera prise, je serai prêt. Espérons qu\'il ne sera pas trop tard.' WHERE `entry` = 2000005040;
UPDATE `db_script_string` SET `content_loc2` = 'Je vais faire de mon mieux pour prendre soin des enfants, grand-mère.' WHERE `entry` = 2000005041;
UPDATE `db_script_string` SET `content_loc2` = 'Nouveautés sur le tableau d\'affichage ! Que les aventuriers et les héros, se réunissent autour du tableau d\'affichage !' WHERE `entry` = 2000005042;
UPDATE `db_script_string` SET `content_loc2` = 'JE VOUS DETRUIERAI TOUS !' WHERE `entry` = 2000005043;
UPDATE `db_script_string` SET `content_loc2` = 'TOUT POUR MOI ET RIEN POUR EUX' WHERE `entry` = 2000005044;
UPDATE `db_script_string` SET `content_loc2` = 'Ne me demandez juste pas où je l\'ai eu...' WHERE `entry` = 2000005045;
UPDATE `db_script_string` SET `content_loc2` = 'Je vais examiner cette prime après mon tour de garde.' WHERE `entry` = 2000005046;
UPDATE `db_script_string` SET `content_loc2` = 'Tu veux aller t\'occuper de la prime de l\'avis de recherche après la fin de la garde ?' WHERE `entry` = 2000005047;
UPDATE `db_script_string` SET `content_loc2` = 'Vous passez un agréable moment ?' WHERE `entry` = 2000005048;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai un autre ouvrage sur le néant.' WHERE `entry` = 2000005049;
UPDATE `db_script_string` SET `content_loc2` = 'Bien vous avez mis la main dessus voyons ce que vous avez là !' WHERE `entry` = 2000005050;
UPDATE `db_script_string` SET `content_loc2` = 'Bien Gazleu !' WHERE `entry` = 2000005051;
UPDATE `db_script_string` SET `content_loc2` = 'Hé, vous là-bas. Vous voulez des bonbons ?' WHERE `entry` = 2000005052;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005053;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005054;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005055;
UPDATE `db_script_string` SET `content_loc2` = 'Bien. Nous avons bousillé nos queues pour tirer tout ce truc jusqu\'ici et vous voulez que nous travaillions encore plus ?' WHERE `entry` = 2000005056;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh… Le bébé pleurnicheur !' WHERE `entry` = 2000005057;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005058;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si ta poupée sait nager !' WHERE `entry` = 2000005059;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J’ai Betsy !' WHERE `entry` = 2000005060;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005061;
UPDATE `db_script_string` SET `content_loc2` = 'J’ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005062;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh… Le bébé pleurnicheur !' WHERE `entry` = 2000005063;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005064;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si ta poupée sait nager !' WHERE `entry` = 2000005065;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J’ai Betsy !' WHERE `entry` = 2000005066;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005067;
UPDATE `db_script_string` SET `content_loc2` = 'J’ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005068;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh… Le bébé pleurnicheur !' WHERE `entry` = 2000005069;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005070;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si ta poupée sait nager !' WHERE `entry` = 2000005071;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J’ai Betsy !' WHERE `entry` = 2000005072;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005073;
UPDATE `db_script_string` SET `content_loc2` = 'J’ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005074;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh… Le bébé pleurnicheur !' WHERE `entry` = 2000005075;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005076;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si ta poupée sait nager !' WHERE `entry` = 2000005077;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005078;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005079;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas mal à Betsy, vilain méchant !' WHERE `entry` = 2000005080;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005081;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005082;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005083;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005084;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005085;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas mal à Betsy, vilain méchant !' WHERE `entry` = 2000005086;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005087;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005088;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005089;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005090;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005091;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas mal à Betsy, vilain méchant !' WHERE `entry` = 2000005092;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005093;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005094;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005095;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005096;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005097;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas mal à Betsy, vilain méchant !' WHERE `entry` = 2000005098;
UPDATE `db_script_string` SET `content_loc2` = 'Pain frais  !' WHERE `entry` = 2000005099;
UPDATE `db_script_string` SET `content_loc2` = 'Brioches, petits pains et miches. Tout frais, sortis du four !' WHERE `entry` = 2000005100;
UPDATE `db_script_string` SET `content_loc2` = 'Pain frais  !' WHERE `entry` = 2000005101;
UPDATE `db_script_string` SET `content_loc2` = 'Brioches, petits pains et miches. Tout frais, sortis du four !' WHERE `entry` = 2000005102;
UPDATE `db_script_string` SET `content_loc2` = 'Jack et Jill me prennent pour une vieille mule ! Je passe ma journée à m\'occuper de l\'eau ici !' WHERE `entry` = 2000005103;
UPDATE `db_script_string` SET `content_loc2` = 'Où est l’eau, Emma ? Va chercher l’eau, Emma ! Si je m’en chargeais pas, y\'en aurait beaucoup qui n\'sauraient pas à quoi r\'semble l’eau.' WHERE `entry` = 2000005104;
UPDATE `db_script_string` SET `content_loc2` = 'Bien sûr je parle toute seule. Mais c\'est le seul moyen d\'avoir une conversation décente dans cette ville.' WHERE `entry` = 2000005105;
UPDATE `db_script_string` SET `content_loc2` = 'Comme si, à mon grand âge, je n’avais pas mieux à faire que de porter des seaux d’eau.' WHERE `entry` = 2000005106;
UPDATE `db_script_string` SET `content_loc2` = 'J’ai l’impression de faire une centaine de fois par jour ce trajet vers le puits pour aller chercher plus d’eau. Aucun respect pour leurs aînés, je vous dis.' WHERE `entry` = 2000005107;
UPDATE `db_script_string` SET `content_loc2` = 'Une impression de déjà-vu. Un instant, j\'ai cru que j\'étais de nouveau à la maison... avant la peste...' WHERE `entry` = 2000005108;
UPDATE `db_script_string` SET `content_loc2` = 'On dit qu’il se métamorphose parfois en corbeau.' WHERE `entry` = 2000005109;
UPDATE `db_script_string` SET `content_loc2` = 'On dit qu’il se métamorphose parfois en corbeau.' WHERE `entry` = 2000005110;
UPDATE `db_script_string` SET `content_loc2` = 'Et alors le lapin l’a mordu et lui a arraché la tête... Je le jure.' WHERE `entry` = 2000005111;
UPDATE `db_script_string` SET `content_loc2` = 'Je le jure, il y a des gens qui les ont vus. Les pandaren existent !' WHERE `entry` = 2000005112;
UPDATE `db_script_string` SET `content_loc2` = 'Tu sais pourquoi les orcs ont des yeux rougeoyants ? Parce qu’ils boivent du sang !' WHERE `entry` = 2000005113;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne pense pas qu\'il y a du poisson dans ces canaux.' WHERE `entry` = 2000005114;
UPDATE `db_script_string` SET `content_loc2` = 'Et c’est comme ça que Lothar a tué trente-six orcs à mains nues !' WHERE `entry` = 2000005115;
UPDATE `db_script_string` SET `content_loc2` = 'Pouah... ce n’est pas un poisson !' WHERE `entry` = 2000005116;
UPDATE `db_script_string` SET `content_loc2` = 'J’ai un ver de terre écrabouillé sur mes chaussures.' WHERE `entry` = 2000005117;
UPDATE `db_script_string` SET `content_loc2` = 'Je crois que je vois quelque chose.' WHERE `entry` = 2000005118;
UPDATE `db_script_string` SET `content_loc2` = 'Pouah... ce n’est pas un poisson !' WHERE `entry` = 2000005119;
UPDATE `db_script_string` SET `content_loc2` = 'Je crois que je vois quelque chose.' WHERE `entry` = 2000005120;
UPDATE `db_script_string` SET `content_loc2` = 'J\'espère que c\'était un poisson !' WHERE `entry` = 2000005121;
UPDATE `db_script_string` SET `content_loc2` = 'On accroche le ver à l’hameçon, on plonge l’hameçon dans l’eau. Le poisson, notre poisson, est dans l’eau.' WHERE `entry` = 2000005122;
UPDATE `db_script_string` SET `content_loc2` = 'Tu t\'imagines ?' WHERE `entry` = 2000005123;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005124;
UPDATE `db_script_string` SET `content_loc2` = 'Incroyable.' WHERE `entry` = 2000005125;
UPDATE `db_script_string` SET `content_loc2` = 'Mon père dit que ce ne sont que des histoires.' WHERE `entry` = 2000005126;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005127;
UPDATE `db_script_string` SET `content_loc2` = 'Incroyable.' WHERE `entry` = 2000005128;
UPDATE `db_script_string` SET `content_loc2` = 'C’est super.' WHERE `entry` = 2000005129;
UPDATE `db_script_string` SET `content_loc2` = 'Incroyable.' WHERE `entry` = 2000005130;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005131;
UPDATE `db_script_string` SET `content_loc2` = 'Dépéchez-vous, chiens ! Nous avons une opération à mener ici !' WHERE `entry` = 2000005132;
UPDATE `db_script_string` SET `content_loc2` = 'Vous passez un agréable moment ?' WHERE `entry` = 2000005133;
UPDATE `db_script_string` SET `content_loc2` = 'Ici, nous avons la Cathédrale de la Lumière, le coeur de l\'illumination spirituelle ici dans Hurlevent.' WHERE `entry` = 2000005134;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, c\'est vrai. Les paladins et les prêtres entrainent leurs compétences ici et sont à la recherche de grandes vérités derrière les murs de la cathédrale.' WHERE `entry` = 2000005135;
UPDATE `db_script_string` SET `content_loc2` = 'Les enfants si vous voulez bien me suivre, nous allons maintenant aller voir le donjon où le roi Anduin Wrynn lui-même est assis sur son trône.' WHERE `entry` = 2000005136;
UPDATE `db_script_string` SET `content_loc2` = 'Ici, nous avons le Donjon de Hurlevent. Construit sur les ruines du Château de Hurlevent qui fut détruit par la Horde lors de la première Grande Guerre.' WHERE `entry` = 2000005137;
UPDATE `db_script_string` SET `content_loc2` = 'Quand la Horde a été vaincue, les hommes sont revenus ici et ont commencé à reconstruire la majestueuse cité comme un témoignage de notre propre survie.' WHERE `entry` = 2000005138;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, bien... nous nous dirigeons maintenant vers les monuments dédiés aux héros des deux Grandes Guerres, la Vallée des Héros. Suivez-moi.' WHERE `entry` = 2000005139;
UPDATE `db_script_string` SET `content_loc2` = 'Ce n\'est pas merveilleux les enfants ? Tous ceux qui entrent dans la ville doivent marcher sous le regard attentif des plus grands héros de nos terres.' WHERE `entry` = 2000005140;
UPDATE `db_script_string` SET `content_loc2` = 'À couper le souffle. Les enfants, quand nous retournerons à l\'école, vous me ferez chacun un rapport oral sur une de ces personnes légendaires.' WHERE `entry` = 2000005141;
UPDATE `db_script_string` SET `content_loc2` = 'Maintenant, jetez un dernier coup d\'oeil avant que nous nous mettons en route vers la Place de la Cathédrale et la grande Cathédrale de la Lumière.' WHERE `entry` = 2000005142;
UPDATE `db_script_string` SET `content_loc2` = 'Ce ne sera jamais...' WHERE `entry` = 2000005143;
UPDATE `db_script_string` SET `content_loc2` = 'Ceci doit être réglé !' WHERE `entry` = 2000005144;
UPDATE `db_script_string` SET `content_loc2` = 'Comment est ce que quelqu\'un peut vivre comme ça !?' WHERE `entry` = 2000005145;
UPDATE `db_script_string` SET `content_loc2` = 'Canard !' WHERE `entry` = 2000005146;
UPDATE `db_script_string` SET `content_loc2` = 'N\'allez pas près du lac ! Il est hanté !' WHERE `entry` = 2000005147;
UPDATE `db_script_string` SET `content_loc2` = 'Une disposition en douze centres de focalisation devrait permettre aux énergies magiques de se former de manière plus solide en ajoutant la stabilité nécessaire.' WHERE `entry` = 2000005148;
UPDATE `db_script_string` SET `content_loc2` = 'Au moins nous ne serons pas aux alentours pour devoir tout nettoyer.' WHERE `entry` = 2000005149;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous n’avons pas suivi les procédures d’initialisation adéquates.' WHERE `entry` = 2000005150;
UPDATE `db_script_string` SET `content_loc2` = 'Les énergies résultantes pourraient s’amoindrir cependant, ce qui pourrait entraîner un flux d’énergie à vous donner une migraine durant des semaines.' WHERE `entry` = 2000005151;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous n’avons pas suivi les procédures d’initialisation adéquates.' WHERE `entry` = 2000005152;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous n’avons pas suivi les procédures d’initialisation adéquates.' WHERE `entry` = 2000005153;
UPDATE `db_script_string` SET `content_loc2` = 'Au moins nous ne serons pas aux alentours pour devoir tout nettoyer.' WHERE `entry` = 2000005154;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n’est-ce pas ce qui a causé les problèmes initiaux avec la formule magique de l’adepte Syleria ?' WHERE `entry` = 2000005155;
UPDATE `db_script_string` SET `content_loc2` = 'Je suppose que ça pourrait marcher si nous disposions de 20 personnes pour nous aider à le lancer.' WHERE `entry` = 2000005156;
UPDATE `db_script_string` SET `content_loc2` = 'Mais qu’adviendra-t-il si le changement de fréquence résultant devait provoquer une réaction magique sur les flux ?' WHERE `entry` = 2000005157;
UPDATE `db_script_string` SET `content_loc2` = 'Lorsque les énergies positivement alignées entre en collision avec la charge négative des énergies, ils ne peuvent pas s\'annuler l\'un l\'autre.' WHERE `entry` = 2000005158;
UPDATE `db_script_string` SET `content_loc2` = 'Cela déséquilibrera cependant le foyer magique et entraînera une vibration inversée dans les éthers.' WHERE `entry` = 2000005159;
UPDATE `db_script_string` SET `content_loc2` = 'Mais cela ne signifierait-il pas croiser les courants ? Ce ne serait pas un vrai problème ?' WHERE `entry` = 2000005160;
UPDATE `db_script_string` SET `content_loc2` = 'Pourquoi ne pas seulement changer l’ordre en vue de compenser les différences de flux ?' WHERE `entry` = 2000005161;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n’est-ce pas ce qui a causé les problèmes initiaux avec la formule magique de l’adepte Syleria ?' WHERE `entry` = 2000005162;
UPDATE `db_script_string` SET `content_loc2` = 'Je pense que non, je n’ai pas besoin qu\'on me fasse sauter une nouvelle fois.' WHERE `entry` = 2000005163;
UPDATE `db_script_string` SET `content_loc2` = 'Maginor dit que les flux alternatifs d’énergie positive créent en fait un flux bien plus stable.' WHERE `entry` = 2000005164;
UPDATE `db_script_string` SET `content_loc2` = 'Mais cela ne signifierait-il pas croiser les courants ? Ce ne serait pas un vrai problème ?' WHERE `entry` = 2000005165;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n’est-ce pas ce qui a causé les problèmes initiaux avec la formule magique de l’adepte Syleria ?' WHERE `entry` = 2000005166;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est vrai que les paladins s\'entrainent ici ?' WHERE `entry` = 2000005167;
UPDATE `db_script_string` SET `content_loc2` = 'Pourquoi devons-nous apprendre ça de toute façon ?' WHERE `entry` = 2000005168;
UPDATE `db_script_string` SET `content_loc2` = 'Si nous inversons les flux de l’Essence, nous pourrons peut-être changer la polarité.' WHERE `entry` = 2000005169;
UPDATE `db_script_string` SET `content_loc2` = 'Et si nous utilisions trois foyers de type Tyrean ? Cela devrait pouvoir résoudre notre problème.' WHERE `entry` = 2000005170;
UPDATE `db_script_string` SET `content_loc2` = 'Waouh, tout ça pour un philtre d’amour. J’espère qu’il en vaut le coup.' WHERE `entry` = 2000005171;
UPDATE `db_script_string` SET `content_loc2` = 'Si nous utilisons l’ordre approprié, cela devrait fonctionner. Il faudra seulement étudier tout cela en détail avant de commencer.' WHERE `entry` = 2000005172;
UPDATE `db_script_string` SET `content_loc2` = 'Le portail se déplacera légèrement. À ce stade, si vous jetez un sort de figement, vous le solidifierez sur place.' WHERE `entry` = 2000005173;
UPDATE `db_script_string` SET `content_loc2` = 'Waouh, tout ça pour un philtre d’amour. J’espère qu’il en vaut le coup.' WHERE `entry` = 2000005174;
UPDATE `db_script_string` SET `content_loc2` = 'Mais si nous le stabilisons à l’aide d’une ancre jetée au niveau du centre d’énergie approprié, cela devrait marcher.' WHERE `entry` = 2000005175;
UPDATE `db_script_string` SET `content_loc2` = 'Et si nous utilisions trois foyers de type Tyrean ? Cela devrait pouvoir résoudre notre problème.' WHERE `entry` = 2000005176;
UPDATE `db_script_string` SET `content_loc2` = 'Si nous utilisons l’ordre approprié, cela devrait fonctionner. Il faudra seulement étudier tout cela en détail avant de commencer.' WHERE `entry` = 2000005177;
UPDATE `db_script_string` SET `content_loc2` = 'Mais si nous le stabilisons à l’aide d’une ancre jetée au niveau du centre d’énergie approprié, cela devrait marcher.' WHERE `entry` = 2000005178;
UPDATE `db_script_string` SET `content_loc2` = 'Waouh, tout ça pour un philtre d’amour. J’espère qu’il en vaut le coup.' WHERE `entry` = 2000005179;
UPDATE `db_script_string` SET `content_loc2` = 'Bonjour, Charys. J\'ai une liste, pouvez vous m\'avoir tout ça , spécialement le dernier ingrédient.' WHERE `entry` = 2000005180;
UPDATE `db_script_string` SET `content_loc2` = 'Bien sur Paige. Soit juste doux.' WHERE `entry` = 2000005181;
UPDATE `db_script_string` SET `content_loc2` = 'Merci, Charys. Viens Paige, ma chérie.' WHERE `entry` = 2000005182;
UPDATE `db_script_string` SET `content_loc2` = 'Maman ? Je peux prendre Flopp comme animal de compagnie ?' WHERE `entry` = 2000005183;
UPDATE `db_script_string` SET `content_loc2` = 'Flopp allait devenir un grand mage. Mais il a été transformé en lapin quand un de ses sorts a mal fonctionné.' WHERE `entry` = 2000005184;
UPDATE `db_script_string` SET `content_loc2` = 'L’étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005185;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005186;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l’atmosphère !' WHERE `entry` = 2000005187;
UPDATE `db_script_string` SET `content_loc2` = 'Vous avez le cafard ? Venez vous amuser au Solitaire bleu !' WHERE `entry` = 2000005188;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005189;
UPDATE `db_script_string` SET `content_loc2` = 'L’étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005190;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez-moi comment boire à l’œil au Solitaire bleu !' WHERE `entry` = 2000005191;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l’atmosphère !' WHERE `entry` = 2000005192;
UPDATE `db_script_string` SET `content_loc2` = 'Boissons gratuites au Solitaire bleu !' WHERE `entry` = 2000005193;
UPDATE `db_script_string` SET `content_loc2` = 'Vous avez le cafard ? Venez vous amuser au Solitaire bleu !' WHERE `entry` = 2000005194;
UPDATE `db_script_string` SET `content_loc2` = 'L’étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005195;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005196;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez-moi comment boire à l’œil au Solitaire bleu !' WHERE `entry` = 2000005197;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l’atmosphère !' WHERE `entry` = 2000005198;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005199;
UPDATE `db_script_string` SET `content_loc2` = 'À la charge !' WHERE `entry` = 2000005200;
UPDATE `db_script_string` SET `content_loc2` = 'À la charge !' WHERE `entry` = 2000005201;
UPDATE `db_script_string` SET `content_loc2` = 'Ahhh, ma précieuse Ameenah ! Que c\'est merveilleux de vous revoir.' WHERE `entry` = 2000005202;
UPDATE `db_script_string` SET `content_loc2` = 'La princesse s\'affaiblit, je peux le sentir !' WHERE `entry` = 2000005203;
UPDATE `db_script_string` SET `content_loc2` = 'Hmm, ne vous opposez pas si je fais !' WHERE `entry` = 2000005204;
UPDATE `db_script_string` SET `content_loc2` = 'Il met du temps à venir, Grillegaufre. N\'avez-vous pas un produit de démonstration ou de quelque chose d\'autre ?' WHERE `entry` = 2000005205;
UPDATE `db_script_string` SET `content_loc2` = 'Soyez le premier de votre bloc a posséder l\'incroyable Fusil Maculateur Electrostatique !' WHERE `entry` = 2000005206;
UPDATE `db_script_string` SET `content_loc2` = 'Déviré de la technologie de pointe offensive de l\'Opération du Soleil Brisé, il fait sauter les taches tenaces avec facilité !' WHERE `entry` = 2000005207;
UPDATE `db_script_string` SET `content_loc2` = 'Taches de vin, taches d\'huile, et même les taches de fond, aucune tache ne résiste au Démaculoblaster électrostatique !' WHERE `entry` = 2000005208;
UPDATE `db_script_string` SET `content_loc2` = 'N\'attendez plus ! Commandez dès à présent et vous recevrez en plus gratuitement ce superbe Moule à gaufres ultrakinétique !' WHERE `entry` = 2000005209;
UPDATE `db_script_string` SET `content_loc2` = 'Je n\'arrêterai jamais. Jamais...' WHERE `entry` = 2000005210;
UPDATE `db_script_string` SET `content_loc2` = 'Hey, que quelqu\'un m\'aide à attraper cette chose !' WHERE `entry` = 2000005211;
UPDATE `db_script_string` SET `content_loc2` = 'Tickets ! Echangez vos tickets de la Foire de Sombrelune ici ! Des prix merveilleux et exotiques vous attendent !' WHERE `entry` = 2000005212;
UPDATE `db_script_string` SET `content_loc2` = 'Peur non ! Toutes les fortunes se profilent pour ceux qui connaissent le chemin.' WHERE `entry` = 2000005213;
UPDATE `db_script_string` SET `content_loc2` = 'Hey ! Aimez vous la sauce ? La sauce est bonne, non ?' WHERE `entry` = 2000005214;
UPDATE `db_script_string` SET `content_loc2` = 'Le Porte-quoi ? Oh , Porte-Cendre ? Jamais entendu parler... Quoi ? Arrétez de m\'ennuyer !' WHERE `entry` = 2000005215;
UPDATE `db_script_string` SET `content_loc2` = 'Tous le monde s\'amuse pour le moment ? C\'est merveilleux ! Bienvenue à la Foire de Sombrelune, le plus grand spectacle de l\'Outreterre ! Assurez-vous d\'avoir parler avec Yebb et ses amis ici avant d\'entrer dans l\'étrange Zoo de Sombrelune de Becquabrach.' WHERE `entry` = 2000005216;
UPDATE `db_script_string` SET `content_loc2` = 'Salutation mes amis, et bienvenue dans le plus grand spectacle d\'Azeroth !$B$BS\'il vous plaît, restez ici et prenez tout ce que nous avons à offrir. Grimpez sur les manèges et voyez nos attractions touristiques ! Etonnez vous avec les merveilles de la Foire de Sombrelune qui ont été découvertes dans ce vaste et merveilleux monde ! Nous n\'avons pas lésiné sur les frais pour vous apporter l\'excitation à laquelle les enfants de tous les âges prendront plaisir !' WHERE `entry` = 2000005217;
UPDATE `db_script_string` SET `content_loc2` = 'Hey, que quelqu\'un m\'aide à attraper cette chose !' WHERE `entry` = 2000005218;
UPDATE `db_script_string` SET `content_loc2` = 'Ceci devrait apporter à Telaar l\'assitance dont elle a besoin !' WHERE `entry` = 2000005219;
UPDATE `db_script_string` SET `content_loc2` = 'SERVITEUR PRIER MOI' WHERE `entry` = 2000005220;
UPDATE `db_script_string` SET `content_loc2` = 'La Foire de Sombrelune est le plus grand évènement de toute l\'Outreterre.' WHERE `entry` = 2000005221;
UPDATE `db_script_string` SET `content_loc2` = 'Ces données seront bien utiles pour le Projet Livre Bleu. Hum, je voulais dire qu\'ils seront très bien pour mon nouveau look. Voyons si nous pouvons dénicher d\'autres données.' WHERE `entry` = 2000005222;
UPDATE `db_script_string` SET `content_loc2` = 'N\'oubliez pas d\'acheter des rafraîchissements et des souvenirs !' WHERE `entry` = 2000005223;
UPDATE `db_script_string` SET `content_loc2` = 'Cela peut être corrigé...' WHERE `entry` = 2000005224;
UPDATE `db_script_string` SET `content_loc2` = 'Et ils appellent ça une soudure !...' WHERE `entry` = 2000005225;
UPDATE `db_script_string` SET `content_loc2` = 'Le mur arrière a été complétement soufflé !' WHERE `entry` = 2000005226;
UPDATE `db_script_string` SET `content_loc2` = 'Venez à moi véritables croyants, et voyons ce que l\'avenir vous réseve !' WHERE `entry` = 2000005227;
UPDATE `db_script_string` SET `content_loc2` = 'J\'aurai du prendre la pillule translucide.' WHERE `entry` = 2000005228;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne suis pas assez payé pour ces excréments de taureaux.' WHERE `entry` = 2000005229;
UPDATE `db_script_string` SET `content_loc2` = 'MOI MECHANT OGRE' WHERE `entry` = 2000005230;
UPDATE `db_script_string` SET `content_loc2` = 'JE SENS LA MORT TOUT AUTOUR' WHERE `entry` = 2000005231;
UPDATE `db_script_string` SET `content_loc2` = 'Plus vous attendez, moins j\'aurais de temps pour votre avenir.' WHERE `entry` = 2000005232;
UPDATE `db_script_string` SET `content_loc2` = 'Asseyez vous par ici et vous allez entendre une cho... *hic* une ch... *hic* une chooo... *hic* Mince !' WHERE `entry` = 2000005233;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne peux pas prendre ces taxes ! Moi F.I.C.A ? F.I.C.A toi même !' WHERE `entry` = 2000005234;
UPDATE `db_script_string` SET `content_loc2` = 'PERSONNE NE ME DEPASSERA' WHERE `entry` = 2000005235;
UPDATE `db_script_string` SET `content_loc2` = 'JE SENS LA MORT TOUT AUTOUR' WHERE `entry` = 2000005236;
UPDATE `db_script_string` SET `content_loc2` = 'Ces feux ont brûlé régulièrement pendant des années. C\'est inhabituel de la part des Trolls.' WHERE `entry` = 2000005237;
UPDATE `db_script_string` SET `content_loc2` = 'Étrange... Ces mosaïques ne ressemblent à aucune des traditions trolls connues.' WHERE `entry` = 2000005238;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, oui, je suis tout à fait certain que cela représente le rassemblement des entités. Fascinant.' WHERE `entry` = 2000005239;
UPDATE `db_script_string` SET `content_loc2` = 'On peut en apprendre long sur une culture par l\'étude de ses déchets.' WHERE `entry` = 2000005240;
UPDATE `db_script_string` SET `content_loc2` = 'Pouah. Des touffes de cheveux emmêlés, des plumes de mue, des bouts d\'os, une matière partiellement brûlée - des vêtements peut-être ?' WHERE `entry` = 2000005241;
