SET NAMES utf8;

UPDATE `mangos_string` SET `content_loc2` = 'Vous devez sélectionner un personnage ou une créature.' WHERE `entry` = 1;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez sélectionner une créature.' WHERE `entry` = 2;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Message Système]:|r %s' WHERE `entry` = 3;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Annonce d\'événement]:|r %s' WHERE `entry` = 4;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune aide n\'est disponible pour cette commande.' WHERE `entry` = 5;
UPDATE `mangos_string` SET `content_loc2` = 'Cette commande n\'existe pas.' WHERE `entry` = 6;
UPDATE `mangos_string` SET `content_loc2` = 'Cette sous-commande n\'existe pas.' WHERE `entry` = 7;
UPDATE `mangos_string` SET `content_loc2` = 'La commande %s possède les sous-commandes suivantes: %s' WHERE `entry` = 8;
UPDATE `mangos_string` SET `content_loc2` = 'Commandes disponibles:' WHERE `entry` = 9;
UPDATE `mangos_string` SET `content_loc2` = 'Syntaxe incorrecte.' WHERE `entry` = 10;
UPDATE `mangos_string` SET `content_loc2` = 'Votre niveau de compte est: %i' WHERE `entry` = 11;
UPDATE `mangos_string` SET `content_loc2` = 'Joueurs en ligne: %u (max: %u) Joueurs dans la file d\'attente: %u (max: %u)' WHERE `entry` = 12;
UPDATE `mangos_string` SET `content_loc2` = 'Serveur en-ligne depuis: %s' WHERE `entry` = 13;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur sauvegardé.' WHERE `entry` = 14;
UPDATE `mangos_string` SET `content_loc2` = 'Tous les joueurs ont été sauvegardés.' WHERE `entry` = 15;
UPDATE `mangos_string` SET `content_loc2` = 'Maîtres-du-jeu disponibles:' WHERE `entry` = 16;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun Maître-du-jeu n\'est actuellement connecté.' WHERE `entry` = 17;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas faire cela en vol.' WHERE `entry` = 18;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas faire cela sur un champ de Bataille.' WHERE `entry` = 19;
UPDATE `mangos_string` SET `content_loc2` = 'La cible est en vol, vous ne pouvez pas faire cela.' WHERE `entry` = 20;
UPDATE `mangos_string` SET `content_loc2` = '%s est en vol, la commande a échoué.' WHERE `entry` = 21;
UPDATE `mangos_string` SET `content_loc2` = 'Vous n\'êtes pas sur une monture, vous ne pouvez donc pas en descendre.' WHERE `entry` = 22;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas faire cela en combattant.' WHERE `entry` = 23;
UPDATE `mangos_string` SET `content_loc2` = 'Vous l\'avez déjà utilisé récemment.' WHERE `entry` = 24;
UPDATE `mangos_string` SET `content_loc2` = 'Le mot de passe n\'a pas été changé (erreur inconnue) !' WHERE `entry` = 25;
UPDATE `mangos_string` SET `content_loc2` = 'Le mot de passe a été changé.' WHERE `entry` = 26;
UPDATE `mangos_string` SET `content_loc2` = 'Le nouveau mot de passe ne correspond pas, ou l\'ancien est mauvais.' WHERE `entry` = 27;
UPDATE `mangos_string` SET `content_loc2` = 'Votre compte est maintenant bloqué.' WHERE `entry` = 28;
UPDATE `mangos_string` SET `content_loc2` = 'Votre compte est maintenant débloqué.' WHERE `entry` = 29;
UPDATE `mangos_string` SET `content_loc2` = ', rang' WHERE `entry` = 30;
UPDATE `mangos_string` SET `content_loc2` = '[connu]' WHERE `entry` = 31;
UPDATE `mangos_string` SET `content_loc2` = '[appris]' WHERE `entry` = 32;
UPDATE `mangos_string` SET `content_loc2` = '[passive]' WHERE `entry` = 33;
UPDATE `mangos_string` SET `content_loc2` = '[talent]' WHERE `entry` = 34;
UPDATE `mangos_string` SET `content_loc2` = '[actif]' WHERE `entry` = 35;
UPDATE `mangos_string` SET `content_loc2` = '[terminé]' WHERE `entry` = 36;
UPDATE `mangos_string` SET `content_loc2` = '(hors ligne)' WHERE `entry` = 37;
UPDATE `mangos_string` SET `content_loc2` = 'on' WHERE `entry` = 38;
UPDATE `mangos_string` SET `content_loc2` = 'off' WHERE `entry` = 39;
UPDATE `mangos_string` SET `content_loc2` = 'Vous êtes: %s' WHERE `entry` = 40;
UPDATE `mangos_string` SET `content_loc2` = 'visible' WHERE `entry` = 41;
UPDATE `mangos_string` SET `content_loc2` = 'invisible' WHERE `entry` = 42;
UPDATE `mangos_string` SET `content_loc2` = 'fait' WHERE `entry` = 43;
UPDATE `mangos_string` SET `content_loc2` = 'Vous' WHERE `entry` = 44;
UPDATE `mangos_string` SET `content_loc2` = '<inconnu>' WHERE `entry` = 45;
UPDATE `mangos_string` SET `content_loc2` = '<erreur>' WHERE `entry` = 46;
UPDATE `mangos_string` SET `content_loc2` = '<personnage inexistant>' WHERE `entry` = 47;
UPDATE `mangos_string` SET `content_loc2` = 'INCONNU' WHERE `entry` = 48;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez avoir le niveau %u pour entrer.' WHERE `entry` = 49;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez avoir le niveau %u et avoir l\'objet %s pour entrer.' WHERE `entry` = 50;
UPDATE `mangos_string` SET `content_loc2` = 'Bonjour ! Prêt pour l\'entrainement ?' WHERE `entry` = 51;
UPDATE `mangos_string` SET `content_loc2` = 'Nombre d\'objets invalide (%u) pour l\'objet %u' WHERE `entry` = 52;
UPDATE `mangos_string` SET `content_loc2` = 'Le courrier ne peut pas contenir plus de %u objets' WHERE `entry` = 53;
UPDATE `mangos_string` SET `content_loc2` = 'Les nouveaux mots de passe ne correspondent pas' WHERE `entry` = 54;
UPDATE `mangos_string` SET `content_loc2` = 'Votre mot de passe ne peut pas dépasser 16 caractères (limite du client). Mot de passe inchangé !' WHERE `entry` = 55;
UPDATE `mangos_string` SET `content_loc2` = 'Message de la journée: \n%s' WHERE `entry` = 56;
UPDATE `mangos_string` SET `content_loc2` = 'Utilisation de la BDD World: %s' WHERE `entry` = 57;
UPDATE `mangos_string` SET `content_loc2` = 'Utilisation de la bibliothèque de scripts: %s' WHERE `entry` = 58;
UPDATE `mangos_string` SET `content_loc2` = 'Utilisation des scripts EventAI: %s' WHERE `entry` = 59;
UPDATE `mangos_string` SET `content_loc2` = 'Je suis occupé pour le moment. Reviens plus tard.' WHERE `entry` = 60;
UPDATE `mangos_string` SET `content_loc2` = 'Nom de compte :' WHERE `entry` = 61;
UPDATE `mangos_string` SET `content_loc2` = 'Mot de passe :' WHERE `entry` = 62;
UPDATE `mangos_string` SET `content_loc2` = 'Annonce générale:' WHERE `entry` = 100;
UPDATE `mangos_string` SET `content_loc2` = 'Map: %u (%s) Zone: %u (%s) Area: %u (%s) Phase: %u\nX: %f Y: %f Z: %f Orientation: %f\ngrid[%u,%u]cell[%u,%u] InstanceID: %u\n ZoneX: %f ZoneY: %f\nGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE `entry` = 101;
UPDATE `mangos_string` SET `content_loc2` = '%s vient tout juste d\'être téléporté.' WHERE `entry` = 102;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas téléporter un joueur dans une instance si vous n\'êtes pas chef de son groupe.' WHERE `entry` = 103;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas aller dans l\'instance du joueur car vous êtes actuellement dans un autre groupe.' WHERE `entry` = 104;
UPDATE `mangos_string` SET `content_loc2` = 'Vous pouvez aller dans l\'instance du joueur sans être dans son groupe, seulement si vous activez le mode MJ.' WHERE `entry` = 105;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas vous téléporter vers le joueur %s d\'une instance à une autre.' WHERE `entry` = 106;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas téléporter le joueur %s d\'une instance à une autre.' WHERE `entry` = 107;
UPDATE `mangos_string` SET `content_loc2` = 'Vous invoquez %s%s.' WHERE `entry` = 108;
UPDATE `mangos_string` SET `content_loc2` = 'Vous êtes invoqué par %s.' WHERE `entry` = 109;
UPDATE `mangos_string` SET `content_loc2` = 'Vous téléportez %s%s vers %s.' WHERE `entry` = 110;
UPDATE `mangos_string` SET `content_loc2` = 'Vous venez d\'être téléporté par %s.' WHERE `entry` = 111;
UPDATE `mangos_string` SET `content_loc2` = 'Le joueur (%s) n\'existe pas.' WHERE `entry` = 112;
UPDATE `mangos_string` SET `content_loc2` = 'Vous apparaissez à l\'emplacement de %s.' WHERE `entry` = 113;
UPDATE `mangos_string` SET `content_loc2` = '%s apparait sur votre emplacement.' WHERE `entry` = 114;
UPDATE `mangos_string` SET `content_loc2` = 'Valeurs incorrectes.' WHERE `entry` = 115;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun personnage sélectionné.' WHERE `entry` = 116;
UPDATE `mangos_string` SET `content_loc2` = '%s n\'est pas dans un groupe.' WHERE `entry` = 117;
UPDATE `mangos_string` SET `content_loc2` = 'Vous changez les PV de %s à %i/%i.' WHERE `entry` = 118;
UPDATE `mangos_string` SET `content_loc2` = '%s a changé vos PV à %i/%i.' WHERE `entry` = 119;
UPDATE `mangos_string` SET `content_loc2` = 'Vous changez la MANA de %s à %i/%i.' WHERE `entry` = 120;
UPDATE `mangos_string` SET `content_loc2` = '%s a changé votre MANA à %i/%i.' WHERE `entry` = 121;
UPDATE `mangos_string` SET `content_loc2` = 'Vous changez l\'ENERGIE de %s à %i/%i.' WHERE `entry` = 122;
UPDATE `mangos_string` SET `content_loc2` = '%s a changé votre ENERGIE à %i/%i.' WHERE `entry` = 123;
UPDATE `mangos_string` SET `content_loc2` = 'Energie actuelle: %u' WHERE `entry` = 124;
UPDATE `mangos_string` SET `content_loc2` = 'Vous changez la RAGE de %s à %i/%i.' WHERE `entry` = 125;
UPDATE `mangos_string` SET `content_loc2` = '%s a changé votre RAGE à %i/%i.' WHERE `entry` = 126;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez changé le niveau de %s à %i.' WHERE `entry` = 127;
UPDATE `mangos_string` SET `content_loc2` = 'GUID %i, faction est %i, flags est %i, npcflag est %i, DY flag est %i' WHERE `entry` = 128;
UPDATE `mangos_string` SET `content_loc2` = 'Mauvaise faction: %u (Non trouvée dans factiontemplate.dbc).' WHERE `entry` = 129;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez changé GUID = %i, faction à %i, flags à %i, npcflag à %i, dyflag à %i.' WHERE `entry` = 130;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez changé le spellflatid = %i, val = %i, mark = %i de %s.' WHERE `entry` = 131;
UPDATE `mangos_string` SET `content_loc2` = '%s a changé votre spellflatid = %i, val = %i, mark = %i.' WHERE `entry` = 132;
UPDATE `mangos_string` SET `content_loc2` = '%s a maintenant accès à tous les trajets aériens (jusqu\'à sa déconnexion).' WHERE `entry` = 133;
UPDATE `mangos_string` SET `content_loc2` = '%s n\'a maintenant plus accès à tous les trajets aériens (seuls ceux visités lui sont accessibles).' WHERE `entry` = 134;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a donné l\'accès à tous les trajets aériens (jusqu\'à votre déconnexion).' WHERE `entry` = 135;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a retiré l\'accès à tous les trajets aériens (seuls ceux visités vous sont accessibles).' WHERE `entry` = 136;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié toutes les vitesses à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 137;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié toutes vos vitesses à %2.2f par rapport à la normale.' WHERE `entry` = 138;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la vitesse à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 139;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre vitesse à %2.2f par rapport à la normale.' WHERE `entry` = 140;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la vitesse de nage à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 141;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre vitesse de nage à %2.2f par rapport à la normale.' WHERE `entry` = 142;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la vitesse de recul à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 143;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre vitesse recul à %2.2f par rapport à la normale.' WHERE `entry` = 144;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la vitesse de vol à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 145;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre vitesse de vol à %2.2f par rapport à la normale.' WHERE `entry` = 146;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la taille à %2.2f par rapport à la normale pour le joueur %s.' WHERE `entry` = 147;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre taille à %2.2f par rapport à la normale.' WHERE `entry` = 148;
UPDATE `mangos_string` SET `content_loc2` = 'Cette monture n\'existe pas.' WHERE `entry` = 149;
UPDATE `mangos_string` SET `content_loc2` = 'Vous donnez une monture à %s.' WHERE `entry` = 150;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a donné une monture.' WHERE `entry` = 151;
UPDATE `mangos_string` SET `content_loc2` = 'UTILISATEUR1: %i, AJOUT: %i, DIF: %i' WHERE `entry` = 152;
UPDATE `mangos_string` SET `content_loc2` = 'Vous prenez tout l\'argent de %s.' WHERE `entry` = 153;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a pris tout votre argent.' WHERE `entry` = 154;
UPDATE `mangos_string` SET `content_loc2` = 'Vous prenez %i pièce(s) de cuivre à %s.' WHERE `entry` = 155;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a pris %i pièce(s) de cuivre.' WHERE `entry` = 156;
UPDATE `mangos_string` SET `content_loc2` = 'Vous donnez %i pièce(s) de cuivre à %s.' WHERE `entry` = 157;
UPDATE `mangos_string` SET `content_loc2` = '%s vous a donné %i pièce(s) de cuivre.' WHERE `entry` = 158;
UPDATE `mangos_string` SET `content_loc2` = 'Vous entendez le son %u.' WHERE `entry` = 159;
UPDATE `mangos_string` SET `content_loc2` = 'UTILISATEUR2: %i, AJOUT: %i, RESULTAT: %i' WHERE `entry` = 160;
UPDATE `mangos_string` SET `content_loc2` = 'Suppression du bit %i dans le champ %i.' WHERE `entry` = 161;
UPDATE `mangos_string` SET `content_loc2` = 'Ajout du bit %i dans le champ %i.' WHERE `entry` = 162;
UPDATE `mangos_string` SET `content_loc2` = 'La table de destinations de téléportation est vide !' WHERE `entry` = 163;
UPDATE `mangos_string` SET `content_loc2` = 'La destination de téléportation est introuvable !' WHERE `entry` = 164;
UPDATE `mangos_string` SET `content_loc2` = 'Paramètre de recherche exigé.' WHERE `entry` = 165;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune destination ne correspond à votre recherche.' WHERE `entry` = 166;
UPDATE `mangos_string` SET `content_loc2` = 'Les destinations trouvées sont:\n%s' WHERE `entry` = 168;
UPDATE `mangos_string` SET `content_loc2` = 'Courrier envoyé à %s' WHERE `entry` = 169;
UPDATE `mangos_string` SET `content_loc2` = 'Vous essayez d\'écouter le son %u mais il n\'existe pas.' WHERE `entry` = 170;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas vous téléporter vers vous-même !' WHERE `entry` = 171;
UPDATE `mangos_string` SET `content_loc2` = 'commande de console du serveur' WHERE `entry` = 172;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez changé la puissance runique de %s à %i/%i.' WHERE `entry` = 173;
UPDATE `mangos_string` SET `content_loc2` = 'La puissance runique de %s a été changé à %i/%i.' WHERE `entry` = 174;
UPDATE `mangos_string` SET `content_loc2` = 'Niveau liquide: %f, profondeur: %f, type: %d, statut: %d' WHERE `entry` = 175;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune sélection.' WHERE `entry` = 200;
UPDATE `mangos_string` SET `content_loc2` = 'Objet GUID est: lowpart %u highpart %X' WHERE `entry` = 201;
UPDATE `mangos_string` SET `content_loc2` = 'Le nom était trop long avec %i caractères.' WHERE `entry` = 202;
UPDATE `mangos_string` SET `content_loc2` = 'Erreur, le nom ne peut contenir que les caractères A-Z et a-z.' WHERE `entry` = 203;
UPDATE `mangos_string` SET `content_loc2` = 'Le surnom est trop long avec %i caractères.' WHERE `entry` = 204;
UPDATE `mangos_string` SET `content_loc2` = 'Pas encore implanté.' WHERE `entry` = 205;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' \'%s\' ajouté à la liste du vendeur avec maxcount \'%i\' et incrtime \'%i\' et extendedcost \'%i\'' WHERE `entry` = 206;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' introuvable dans la Base de données.' WHERE `entry` = 207;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' \'%s\' supprimé de la liste du vendeur.' WHERE `entry` = 208;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' introuvable dans la liste du vendeur.' WHERE `entry` = 209;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' déjà présent dans la liste du vendeur.' WHERE `entry` = 210;
UPDATE `mangos_string` SET `content_loc2` = 'Les sorts de %s ont été réinitialisés.' WHERE `entry` = 211;
UPDATE `mangos_string` SET `content_loc2` = 'Les sorts de %s seront réinitialisés lors de la prochaine connexion.' WHERE `entry` = 212;
UPDATE `mangos_string` SET `content_loc2` = 'Les talents de %s ont été réinitialisés.' WHERE `entry` = 213;
UPDATE `mangos_string` SET `content_loc2` = 'Les talents de %s seront réinitialisés lors de la prochaine connexion.' WHERE `entry` = 214;
UPDATE `mangos_string` SET `content_loc2` = 'Vos sorts ont été réinitialisés.' WHERE `entry` = 215;
UPDATE `mangos_string` SET `content_loc2` = 'Vos talents ont été réinitialisés.' WHERE `entry` = 216;
UPDATE `mangos_string` SET `content_loc2` = 'Paramètre \'%s\' inconnu pour la commande .resetall. Donnez un nom correct de paramètre.' WHERE `entry` = 217;
UPDATE `mangos_string` SET `content_loc2` = 'Les sorts seront réinitialisés pour tous les joueurs en ligne. Reconnexion fortement recommandé !' WHERE `entry` = 218;
UPDATE `mangos_string` SET `content_loc2` = 'Les talents seront réinitialisés pour tous les joueurs en ligne. Reconnexion fortement recommandé !' WHERE `entry` = 219;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) Aucun point de passage trouvé.' WHERE `entry` = 220;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) Dernier point de passage introuvable.' WHERE `entry` = 221;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) Aucun point de passage trouvé - Utilisez \'wpguid\'. Maintenant essayez de le trouver avec sa position...' WHERE `entry` = 222;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) Aucun point de passage trouvé - C\'est une erreur de base de données (single float).' WHERE `entry` = 223;
UPDATE `mangos_string` SET `content_loc2` = 'Créature sélectionnée ignorée - Le GUID fourni est en cours d\'utilisation.' WHERE `entry` = 224;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) introuvable' WHERE `entry` = 225;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez sélectionner un point de passage visible.' WHERE `entry` = 226;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun point de passage visible trouvé.' WHERE `entry` = 227;
UPDATE `mangos_string` SET `content_loc2` = 'Impossible de créer un point de passage visible avec la créature d\'ID: %d.' WHERE `entry` = 228;
UPDATE `mangos_string` SET `content_loc2` = 'Tous les points de passage visibles ont été supprimés.' WHERE `entry` = 229;
UPDATE `mangos_string` SET `content_loc2` = 'Impossible de créer un point de passage de créature avec l\'ID: %d' WHERE `entry` = 230;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun GUID fourni.' WHERE `entry` = 231;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun numéro de point de passage fourni.' WHERE `entry` = 232;
UPDATE `mangos_string` SET `content_loc2` = 'Un argument est requis pour \'%s\'.' WHERE `entry` = 233;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage %i ajouté au GUID: %d' WHERE `entry` = 234;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage %d ajouté.' WHERE `entry` = 235;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage changé.' WHERE `entry` = 236;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage %s modifié.' WHERE `entry` = 237;
UPDATE `mangos_string` SET `content_loc2` = 'Points de passage exportés avec succès.' WHERE `entry` = 238;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun point de passage trouvé dans la base de données.' WHERE `entry` = 239;
UPDATE `mangos_string` SET `content_loc2` = 'Fichier importé.' WHERE `entry` = 240;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage supprimé.' WHERE `entry` = 241;
UPDATE `mangos_string` SET `content_loc2` = 'Attention: impossible de supprimer le point de passage du monde avec ID: %d' WHERE `entry` = 242;
UPDATE `mangos_string` SET `content_loc2` = 'Cela arrive lorsque le point de passage est trop loin de votre personnage.' WHERE `entry` = 243;
UPDATE `mangos_string` SET `content_loc2` = 'Le point de passage a été supprimé de la base de données, mais pas depuis ce monde.' WHERE `entry` = 244;
UPDATE `mangos_string` SET `content_loc2` = 'Ils disparaîtront après un redémarrage du serveur.' WHERE `entry` = 245;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage %d: Info pour la créature: %s, GUID: %d' WHERE `entry` = 246;
UPDATE `mangos_string` SET `content_loc2` = 'Temps d\'attente: %d' WHERE `entry` = 247;
UPDATE `mangos_string` SET `content_loc2` = 'Modèle %d: %d' WHERE `entry` = 248;
UPDATE `mangos_string` SET `content_loc2` = 'Emote: %d' WHERE `entry` = 249;
UPDATE `mangos_string` SET `content_loc2` = 'Sort: %d' WHERE `entry` = 250;
UPDATE `mangos_string` SET `content_loc2` = 'Texte %d (ID: %i): %s' WHERE `entry` = 251;
UPDATE `mangos_string` SET `content_loc2` = 'ScriptIA: %s' WHERE `entry` = 252;
UPDATE `mangos_string` SET `content_loc2` = 'Changement forcé du nom du joueur %s à la prochaine connexion.' WHERE `entry` = 253;
UPDATE `mangos_string` SET `content_loc2` = 'Changement forcé du nom du joueur %s (GUID #%u) à la prochaine connexion.' WHERE `entry` = 254;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage de créature (GUID: %u) introuvable.' WHERE `entry` = 255;
UPDATE `mangos_string` SET `content_loc2` = 'Impossible de trouver le PNJ...' WHERE `entry` = 256;
UPDATE `mangos_string` SET `content_loc2` = 'Type de mouvement de créature modifié à \'%s\', points de passage supprimés (si existants).' WHERE `entry` = 257;
UPDATE `mangos_string` SET `content_loc2` = 'Type de mouvement de créature modifié à \'%s\', points de passage non supprimés.' WHERE `entry` = 258;
UPDATE `mangos_string` SET `content_loc2` = 'Valeur incorrecte, utilisez ON ou OFF.' WHERE `entry` = 259;
UPDATE `mangos_string` SET `content_loc2` = 'Valeur sauvegardée.' WHERE `entry` = 260;
UPDATE `mangos_string` SET `content_loc2` = 'Valeur sauvegardée, nettoyez le cache de votre client.' WHERE `entry` = 261;
UPDATE `mangos_string` SET `content_loc2` = 'Areatrigger ID %u non trouvé !' WHERE `entry` = 262;
UPDATE `mangos_string` SET `content_loc2` = 'Carte ou coordonnées de destination invalides (X: %f Y: %f MapId: %u).' WHERE `entry` = 263;
UPDATE `mangos_string` SET `content_loc2` = 'Coordonnées de zone invalides (X: %f Y: %f AreaId: %u)' WHERE `entry` = 264;
UPDATE `mangos_string` SET `content_loc2` = 'La zone %u (%s) est une partie de l\'instance %u (%s)' WHERE `entry` = 265;
UPDATE `mangos_string` SET `content_loc2` = 'Rien n\'a été trouvé !' WHERE `entry` = 266;
UPDATE `mangos_string` SET `content_loc2` = 'Objet introuvable !' WHERE `entry` = 267;
UPDATE `mangos_string` SET `content_loc2` = 'Créature introuvable !' WHERE `entry` = 268;
UPDATE `mangos_string` SET `content_loc2` = 'Attention: La recherche a donnée plusieurs résultats, vous devriez être téléporté sur la première créature trouvée dans la base de données.' WHERE `entry` = 269;
UPDATE `mangos_string` SET `content_loc2` = 'Créature supprimée.' WHERE `entry` = 270;
UPDATE `mangos_string` SET `content_loc2` = 'Créature déplacée.' WHERE `entry` = 271;
UPDATE `mangos_string` SET `content_loc2` = 'La créature (GUID: %u) doit être sur la même carte que le joueur !' WHERE `entry` = 272;
UPDATE `mangos_string` SET `content_loc2` = 'Game Object (GUID: %u) introuvable.' WHERE `entry` = 273;
UPDATE `mangos_string` SET `content_loc2` = 'Game Object (GUID: %u) a des références sur une créature introuvable %u, impossible de le supprimer.' WHERE `entry` = 274;
UPDATE `mangos_string` SET `content_loc2` = 'Game Object (GUID: %u) supprimé.' WHERE `entry` = 275;
UPDATE `mangos_string` SET `content_loc2` = 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) tourné.' WHERE `entry` = 276;
UPDATE `mangos_string` SET `content_loc2` = 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) déplacé.' WHERE `entry` = 277;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez sélectionner un vendeur' WHERE `entry` = 278;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez indiquer un ID pour l\'équipement' WHERE `entry` = 279;
UPDATE `mangos_string` SET `content_loc2` = 'Le vendeur possède trop d\'équipements (max 128).' WHERE `entry` = 280;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas vous kicker vous-même, déconnectez-vous plutôt.' WHERE `entry` = 281;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur %s kické.' WHERE `entry` = 282;
UPDATE `mangos_string` SET `content_loc2` = 'Acceptation des chuchotements: %s' WHERE `entry` = 284;
UPDATE `mangos_string` SET `content_loc2` = 'Acceptation des chuchotements: ON' WHERE `entry` = 285;
UPDATE `mangos_string` SET `content_loc2` = 'Acceptation des chuchotements: OFF' WHERE `entry` = 286;
UPDATE `mangos_string` SET `content_loc2` = 'Créature (GUID: %u) introuvable' WHERE `entry` = 287;
UPDATE `mangos_string` SET `content_loc2` = 'Nombre de tickets: %i Affichage des nouveaux tickets: %s' WHERE `entry` = 288;
UPDATE `mangos_string` SET `content_loc2` = 'Nouveau ticket de %s.' WHERE `entry` = 289;
UPDATE `mangos_string` SET `content_loc2` = 'Ticket de %s (Dernière mise à jour: %s):\n%s' WHERE `entry` = 290;
UPDATE `mangos_string` SET `content_loc2` = 'Affichage des nouveaux tickets: ON' WHERE `entry` = 291;
UPDATE `mangos_string` SET `content_loc2` = 'Affichage des nouveaux tickets: OFF' WHERE `entry` = 292;
UPDATE `mangos_string` SET `content_loc2` = 'Ticket %i inexistant.' WHERE `entry` = 293;
UPDATE `mangos_string` SET `content_loc2` = 'Tous les tickets ont été supprimés.' WHERE `entry` = 294;
UPDATE `mangos_string` SET `content_loc2` = 'Ticket du joueur %s supprimé.' WHERE `entry` = 295;
UPDATE `mangos_string` SET `content_loc2` = 'Ticket supprimé.' WHERE `entry` = 296;
UPDATE `mangos_string` SET `content_loc2` = 'Distance d\'apparition changée à: %f' WHERE `entry` = 297;
UPDATE `mangos_string` SET `content_loc2` = 'Temps d\'apparition changé à: %i' WHERE `entry` = 298;
UPDATE `mangos_string` SET `content_loc2` = 'L\'honneur de %s a été modifié à %u !' WHERE `entry` = 299;
UPDATE `mangos_string` SET `content_loc2` = 'Votre tchat a été désactivé pour %u minutes.' WHERE `entry` = 300;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez désactivé le tchat de %s pour %u minutes.' WHERE `entry` = 301;
UPDATE `mangos_string` SET `content_loc2` = 'Le tchat du joueur est déjà activé.' WHERE `entry` = 302;
UPDATE `mangos_string` SET `content_loc2` = 'Votre tchat a été activé.' WHERE `entry` = 303;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez activé le tchat de %s.' WHERE `entry` = 304;
UPDATE `mangos_string` SET `content_loc2` = 'La faction de réputation %s (%u) de %s a été modifié à %5d !' WHERE `entry` = 305;
UPDATE `mangos_string` SET `content_loc2` = 'Les points d\'arène de %s ont été modifiés à %u !' WHERE `entry` = 306;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune faction trouvé.' WHERE `entry` = 307;
UPDATE `mangos_string` SET `content_loc2` = 'Faction %i inconnu !' WHERE `entry` = 308;
UPDATE `mangos_string` SET `content_loc2` = 'Paramètre %s invalide' WHERE `entry` = 309;
UPDATE `mangos_string` SET `content_loc2` = 'delta doit être compris entre 0 et %d (inclus)' WHERE `entry` = 310;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE `entry` = 311;
UPDATE `mangos_string` SET `content_loc2` = '[visible]' WHERE `entry` = 312;
UPDATE `mangos_string` SET `content_loc2` = '[en guerre]' WHERE `entry` = 313;
UPDATE `mangos_string` SET `content_loc2` = '[paix obligatoire]' WHERE `entry` = 314;
UPDATE `mangos_string` SET `content_loc2` = '[caché]' WHERE `entry` = 315;
UPDATE `mangos_string` SET `content_loc2` = '[invisible obligatoire]' WHERE `entry` = 316;
UPDATE `mangos_string` SET `content_loc2` = '[inactif]' WHERE `entry` = 317;
UPDATE `mangos_string` SET `content_loc2` = 'Détesté' WHERE `entry` = 318;
UPDATE `mangos_string` SET `content_loc2` = 'Hostile' WHERE `entry` = 319;
UPDATE `mangos_string` SET `content_loc2` = 'Inamical' WHERE `entry` = 320;
UPDATE `mangos_string` SET `content_loc2` = 'Neutre' WHERE `entry` = 321;
UPDATE `mangos_string` SET `content_loc2` = 'Amical' WHERE `entry` = 322;
UPDATE `mangos_string` SET `content_loc2` = 'Honoré' WHERE `entry` = 323;
UPDATE `mangos_string` SET `content_loc2` = 'Révéré' WHERE `entry` = 324;
UPDATE `mangos_string` SET `content_loc2` = 'Exalté' WHERE `entry` = 325;
UPDATE `mangos_string` SET `content_loc2` = 'La faction %s (%u) ne peut pas avoir de réputation.' WHERE `entry` = 326;
UPDATE `mangos_string` SET `content_loc2` = '[aucune réputation]' WHERE `entry` = 327;
UPDATE `mangos_string` SET `content_loc2` = 'Personnages sur le compte %s (Id: %u)' WHERE `entry` = 328;
UPDATE `mangos_string` SET `content_loc2` = '%s (GUID %u)' WHERE `entry` = 329;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun joueur trouvé !' WHERE `entry` = 330;
UPDATE `mangos_string` SET `content_loc2` = 'Extended item cost %u inexistant' WHERE `entry` = 331;
UPDATE `mangos_string` SET `content_loc2` = 'Mode MJ activé' WHERE `entry` = 332;
UPDATE `mangos_string` SET `content_loc2` = 'Mode MJ désactivé' WHERE `entry` = 333;
UPDATE `mangos_string` SET `content_loc2` = 'Logo Tchat MJ activé' WHERE `entry` = 334;
UPDATE `mangos_string` SET `content_loc2` = 'Logo Tchat MJ désactivé' WHERE `entry` = 335;
UPDATE `mangos_string` SET `content_loc2` = 'Vous réparez tous les équipements de %s.' WHERE `entry` = 336;
UPDATE `mangos_string` SET `content_loc2` = 'Tous vos équipements ont été réparés par %s.' WHERE `entry` = 337;
UPDATE `mangos_string` SET `content_loc2` = 'Vous configurez le mode Marche-sur-eau à %s pour %s.' WHERE `entry` = 338;
UPDATE `mangos_string` SET `content_loc2` = 'Votre mode Marche-sur-eau a été configuré à %s par %s.' WHERE `entry` = 339;
UPDATE `mangos_string` SET `content_loc2` = '%s est en train de vous suivre.' WHERE `entry` = 340;
UPDATE `mangos_string` SET `content_loc2` = '%s ne vous suit plus.' WHERE `entry` = 341;
UPDATE `mangos_string` SET `content_loc2` = '%s n\'est plus en train de vous suivre.' WHERE `entry` = 342;
UPDATE `mangos_string` SET `content_loc2` = 'La créature (Entry: %u) ne peut pas être domptée.' WHERE `entry` = 343;
UPDATE `mangos_string` SET `content_loc2` = 'Vous possédez déjà un familier.' WHERE `entry` = 344;
UPDATE `mangos_string` SET `content_loc2` = 'Customisation forcée du player %s à la prochaine connexion.' WHERE `entry` = 345;
UPDATE `mangos_string` SET `content_loc2` = 'Customisation forcée du joueur %s (GUID #%u) à la prochaine connexion.' WHERE `entry` = 346;
UPDATE `mangos_string` SET `content_loc2` = 'TaxiNode d\'ID %u introuvable !' WHERE `entry` = 347;
UPDATE `mangos_string` SET `content_loc2` = 'Le Gameobject (Entry: %u) possède un champ data invalide, et ne peut donc pas être implanté.' WHERE `entry` = 348;
UPDATE `mangos_string` SET `content_loc2` = '%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s' WHERE `entry` = 349;
UPDATE `mangos_string` SET `content_loc2` = '%d (idx:%d) - [%s %s] %s %s' WHERE `entry` = 350;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun titre trouvé !' WHERE `entry` = 351;
UPDATE `mangos_string` SET `content_loc2` = 'Titre invalide (id: %u)' WHERE `entry` = 352;
UPDATE `mangos_string` SET `content_loc2` = 'Le titre %u (%s) a été ajouté à la liste des titres connus du joueur %s.' WHERE `entry` = 353;
UPDATE `mangos_string` SET `content_loc2` = 'Le titre %u (%s) a été retiré de la liste des titres connus du joueur %s.' WHERE `entry` = 354;
UPDATE `mangos_string` SET `content_loc2` = 'Le titre %u (%s) est devenu le titre courant du joueur %s.' WHERE `entry` = 355;
UPDATE `mangos_string` SET `content_loc2` = 'Le titre courant du joueur %s a été réinitialisé.' WHERE `entry` = 356;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Message Système]:|r Scripts rechargés' WHERE `entry` = 400;
UPDATE `mangos_string` SET `content_loc2` = 'Vous modifiez le niveau de sécurité du compte %s à %i.' WHERE `entry` = 401;
UPDATE `mangos_string` SET `content_loc2` = '%s a modifié votre niveau de sécurité à %i.' WHERE `entry` = 402;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez un niveau de sécurité trop bas pour cela.' WHERE `entry` = 403;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvements de la créature désactivés.' WHERE `entry` = 404;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvements de la créature activés.' WHERE `entry` = 405;
UPDATE `mangos_string` SET `content_loc2` = 'La météorologie ne peut pas être changée dans cette zone.' WHERE `entry` = 406;
UPDATE `mangos_string` SET `content_loc2` = 'Le système météorologique est désactivé.' WHERE `entry` = 407;
UPDATE `mangos_string` SET `content_loc2` = '%s est banni pendant %s. Motif: %s.' WHERE `entry` = 408;
UPDATE `mangos_string` SET `content_loc2` = '%s est banni de manière permanente pour %s.' WHERE `entry` = 409;
UPDATE `mangos_string` SET `content_loc2` = '%s %s introuvable.' WHERE `entry` = 410;
UPDATE `mangos_string` SET `content_loc2` = '%s débanni.' WHERE `entry` = 411;
UPDATE `mangos_string` SET `content_loc2` = 'Il est survenu une erreur lors du débanissement de %s.' WHERE `entry` = 412;
UPDATE `mangos_string` SET `content_loc2` = 'Compte inexistant: %s' WHERE `entry` = 413;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a aucun personnage correspondant.' WHERE `entry` = 414;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a aucune adresse IP correspondante dans la liste des bannis.' WHERE `entry` = 415;
UPDATE `mangos_string` SET `content_loc2` = 'Le compte %s n\'a jamais été banni.' WHERE `entry` = 416;
UPDATE `mangos_string` SET `content_loc2` = 'Historique de bannissement du compte %s:' WHERE `entry` = 417;
UPDATE `mangos_string` SET `content_loc2` = 'Date de bannissement: %s Durée: %s Etat: %s Motif: %s Par: %s' WHERE `entry` = 418;
UPDATE `mangos_string` SET `content_loc2` = 'Inf.' WHERE `entry` = 419;
UPDATE `mangos_string` SET `content_loc2` = 'Jamais' WHERE `entry` = 420;
UPDATE `mangos_string` SET `content_loc2` = 'Oui' WHERE `entry` = 421;
UPDATE `mangos_string` SET `content_loc2` = 'Non' WHERE `entry` = 422;
UPDATE `mangos_string` SET `content_loc2` = 'IP: %s\nDate ban: %s\nDate deban: %s\nTemps restant: %s\nRaison: %s\nBanni par: %s' WHERE `entry` = 423;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a pas d\'ip bannie correspondante.' WHERE `entry` = 424;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a pas de compte correspondant.' WHERE `entry` = 425;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a pas de compte banni correspondant au nom de personnage donné.' WHERE `entry` = 426;
UPDATE `mangos_string` SET `content_loc2` = 'Les IP suivantes correspondent à votre recherche:' WHERE `entry` = 427;
UPDATE `mangos_string` SET `content_loc2` = 'Les comptes suivant correspondent à votre requête:' WHERE `entry` = 428;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris plusieurs sorts/compétences.' WHERE `entry` = 429;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris tous les sorts de votre classe.' WHERE `entry` = 430;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris tous les talents de votre classe.' WHERE `entry` = 431;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris toutes les langues.' WHERE `entry` = 432;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris toutes les compétences de métier et recettes.' WHERE `entry` = 433;
UPDATE `mangos_string` SET `content_loc2` = 'Impossible de trouver \'%s\'.' WHERE `entry` = 434;
UPDATE `mangos_string` SET `content_loc2` = 'ID de l\'équipement invalide: %u' WHERE `entry` = 435;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun équipement trouvé !' WHERE `entry` = 436;
UPDATE `mangos_string` SET `content_loc2` = 'ID de l\'objet invalide: %u' WHERE `entry` = 437;
UPDATE `mangos_string` SET `content_loc2` = 'Equipements %u trouvés: %u (inventaire %u courrier %u autel %u guilde %u)' WHERE `entry` = 438;
UPDATE `mangos_string` SET `content_loc2` = 'Objets %u trouvés: %u' WHERE `entry` = 439;
UPDATE `mangos_string` SET `content_loc2` = 'ID de créature invalide: %u' WHERE `entry` = 440;
UPDATE `mangos_string` SET `content_loc2` = 'Créatures %u trouvées: %u' WHERE `entry` = 441;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune région trouvée !' WHERE `entry` = 442;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun SET d\'équipements trouvé !' WHERE `entry` = 443;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune compétence trouvée !' WHERE `entry` = 444;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun sort trouvé !' WHERE `entry` = 445;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune quête trouvée !' WHERE `entry` = 446;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune créature trouvée !' WHERE `entry` = 447;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun objet trouvé !' WHERE `entry` = 448;
UPDATE `mangos_string` SET `content_loc2` = 'Cimetière #%u inexistant.' WHERE `entry` = 449;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière #%u est déjà lié à la zone #%u (actuelle).' WHERE `entry` = 450;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière #%u est lié à la zone #%u (actuelle).' WHERE `entry` = 451;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière #%u ne peut pas être lié à la sous-zone ou la zone est inexistance #%u (erreur interne).' WHERE `entry` = 452;
UPDATE `mangos_string` SET `content_loc2` = 'Aucune faction dans le cimetière d\'id = #%u, corrigez votre BDD.' WHERE `entry` = 454;
UPDATE `mangos_string` SET `content_loc2` = 'équipe invalide, corrigez votre BDD.' WHERE `entry` = 455;
UPDATE `mangos_string` SET `content_loc2` = 'chaque' WHERE `entry` = 456;
UPDATE `mangos_string` SET `content_loc2` = 'alliance' WHERE `entry` = 457;
UPDATE `mangos_string` SET `content_loc2` = 'horde' WHERE `entry` = 458;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière #%u (faction: %s) est le plus proche lié à la zone #%u.' WHERE `entry` = 459;
UPDATE `mangos_string` SET `content_loc2` = 'La zone #%u n\'a aucun cimetière lié.' WHERE `entry` = 460;
UPDATE `mangos_string` SET `content_loc2` = 'La zone #%u n\'a aucun cimetière lié pour la faction: %s.' WHERE `entry` = 461;
UPDATE `mangos_string` SET `content_loc2` = 'L\'emplacement de téléportation existe déjà !' WHERE `entry` = 462;
UPDATE `mangos_string` SET `content_loc2` = 'Emplacement de téléportation ajouté.' WHERE `entry` = 463;
UPDATE `mangos_string` SET `content_loc2` = 'Emplacement de téléportation NON ajouté: erreur dans la base de données.' WHERE `entry` = 464;
UPDATE `mangos_string` SET `content_loc2` = 'Emplacement de téléportation supprimé.' WHERE `entry` = 465;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun TaxiNode trouvé !' WHERE `entry` = 466;
UPDATE `mangos_string` SET `content_loc2` = 'La cible a %d auras:' WHERE `entry` = 467;
UPDATE `mangos_string` SET `content_loc2` = 'id: %d eff: %d type: %d durée: %d durée max: %d nom: %s%s%s lanceur de sort: %s %u' WHERE `entry` = 468;
UPDATE `mangos_string` SET `content_loc2` = 'La cible a %d auras de type %d:' WHERE `entry` = 469;
UPDATE `mangos_string` SET `content_loc2` = 'id: %d eff: %d nom: %s%s%s lanceur de sort: %s %u' WHERE `entry` = 470;
UPDATE `mangos_string` SET `content_loc2` = 'Quête %u introuvable.' WHERE `entry` = 471;
UPDATE `mangos_string` SET `content_loc2` = 'La quête %u est démarrée par un équipement. Pour un fonctionnement correct, merci d\'ajouter l\'équipement dans l\'inventaire et de démarrer la quête normalement: .additem %u' WHERE `entry` = 472;
UPDATE `mangos_string` SET `content_loc2` = 'Quête supprimée.' WHERE `entry` = 473;
UPDATE `mangos_string` SET `content_loc2` = '[récompensé]' WHERE `entry` = 474;
UPDATE `mangos_string` SET `content_loc2` = '[terminé]' WHERE `entry` = 475;
UPDATE `mangos_string` SET `content_loc2` = '[actif]' WHERE `entry` = 476;
UPDATE `mangos_string` SET `content_loc2` = 'Mode de vol de %s: %s' WHERE `entry` = 477;
UPDATE `mangos_string` SET `content_loc2` = 'Opcode %u envoyé à %s' WHERE `entry` = 478;
UPDATE `mangos_string` SET `content_loc2` = 'Personnage chargé avec succès !' WHERE `entry` = 479;
UPDATE `mangos_string` SET `content_loc2` = 'Echec lors du chargement du personnage !' WHERE `entry` = 480;
UPDATE `mangos_string` SET `content_loc2` = 'Personnage exporté avec succès !' WHERE `entry` = 481;
UPDATE `mangos_string` SET `content_loc2` = 'Echec lors de l\'exportation du personnage !' WHERE `entry` = 482;
UPDATE `mangos_string` SET `content_loc2` = 'Sort %u défaillant et impossible à incanter ou apprendre !' WHERE `entry` = 483;
UPDATE `mangos_string` SET `content_loc2` = 'La compétence %u (%s) pour le joueur %s a été mise à %u avec un maximum de %u (sans bonus (talents) permanent).' WHERE `entry` = 484;
UPDATE `mangos_string` SET `content_loc2` = 'Le joueur %s doit posséder la compétence %u (%s) avant d\'utiliser cette commande.' WHERE `entry` = 485;
UPDATE `mangos_string` SET `content_loc2` = 'ID de compétence invalide (%u)' WHERE `entry` = 486;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris les sorts/compétences de base du MJ.' WHERE `entry` = 487;
UPDATE `mangos_string` SET `content_loc2` = 'Vous connaissez déjà ce sort.' WHERE `entry` = 488;
UPDATE `mangos_string` SET `content_loc2` = 'La cible (%s) connait déjà ce sort.' WHERE `entry` = 489;
UPDATE `mangos_string` SET `content_loc2` = '%s ne connait pas ce sort.' WHERE `entry` = 490;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez déjà oublié ce sort.' WHERE `entry` = 491;
UPDATE `mangos_string` SET `content_loc2` = 'Tous les temps de rechargement des sorts ont été supprimés pour %s.' WHERE `entry` = 492;
UPDATE `mangos_string` SET `content_loc2` = 'Le temps de rechargement du sort %u a été supprimé pour %s.' WHERE `entry` = 493;
UPDATE `mangos_string` SET `content_loc2` = 'Commande: Additem, ID de l\'équipement = %i, quantité = %i' WHERE `entry` = 494;
UPDATE `mangos_string` SET `content_loc2` = 'Commande: Additemset, ID du SET = %i' WHERE `entry` = 495;
UPDATE `mangos_string` SET `content_loc2` = 'Suppression de l\'équipement d\'ID = %i, Quantité = %i de %s' WHERE `entry` = 496;
UPDATE `mangos_string` SET `content_loc2` = 'Impossible de créer l\'équipement \'%i\' (quantité: %i)' WHERE `entry` = 497;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez spécifier un nom de guilde !' WHERE `entry` = 498;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur introuvable !' WHERE `entry` = 499;
UPDATE `mangos_string` SET `content_loc2` = 'Le joueur possède déjà une guilde !' WHERE `entry` = 500;
UPDATE `mangos_string` SET `content_loc2` = 'Echec lors de la création de la guilde (déjà existante ?)' WHERE `entry` = 501;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun équipement du SET \'%u\' n\'a été trouvé.' WHERE `entry` = 502;
UPDATE `mangos_string` SET `content_loc2` = 'La distance est: (3D) %f (2D) %f yards.' WHERE `entry` = 503;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' \'%s\' Emplacement de l\'équipement %i' WHERE `entry` = 504;
UPDATE `mangos_string` SET `content_loc2` = 'Equipement \'%i\' inexistant.' WHERE `entry` = 505;
UPDATE `mangos_string` SET `content_loc2` = 'L\'équipement \'%i\' \'%s\' a été ajouté à l\'emplacement %i' WHERE `entry` = 506;
UPDATE `mangos_string` SET `content_loc2` = 'Echec lors de la sauvegarde d\'un équipement !' WHERE `entry` = 507;
UPDATE `mangos_string` SET `content_loc2` = '%d - propriétaire: %s (guid: %u compte: %u ) %s' WHERE `entry` = 508;
UPDATE `mangos_string` SET `content_loc2` = '%d - expéditeur: %s (guid: %u compte: %u ) destinataire: %s (guid: %u compte: %u ) %s' WHERE `entry` = 509;
UPDATE `mangos_string` SET `content_loc2` = '%d - propriétaire: %s (guid: %u compte: %u ) %s' WHERE `entry` = 510;
UPDATE `mangos_string` SET `content_loc2` = 'Mauvais type de lien !' WHERE `entry` = 511;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r' WHERE `entry` = 512;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE `entry` = 513;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r' WHERE `entry` = 514;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE `entry` = 515;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r' WHERE `entry` = 516;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r' WHERE `entry` = 517;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r' WHERE `entry` = 518;
UPDATE `mangos_string` SET `content_loc2` = '|cffffffff|Htele:%s|h[%s]|h|r' WHERE `entry` = 519;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hspell:%d|h[%s]|h|r' WHERE `entry` = 520;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE `entry` = 521;
UPDATE `mangos_string` SET `content_loc2` = 'Gameobject (Entry: %u) introuvable.' WHERE `entry` = 522;
UPDATE `mangos_string` SET `content_loc2` = '>> Game Object %s (GUID: %u) %f %f %f. Orientation %f.' WHERE `entry` = 523;
UPDATE `mangos_string` SET `content_loc2` = 'Objet sélectionné:\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f Carte: %u\nOrientation: %f' WHERE `entry` = 524;
UPDATE `mangos_string` SET `content_loc2` = '>> Le Game Object \'%i\' (%s) (GUID: %i) a été ajouté à \'%f %f %f\'.' WHERE `entry` = 525;
UPDATE `mangos_string` SET `content_loc2` = '%s (lowguid: %u) pile de générateurs de mouvements:' WHERE `entry` = 526;
UPDATE `mangos_string` SET `content_loc2` = 'Au repos' WHERE `entry` = 527;
UPDATE `mangos_string` SET `content_loc2` = 'Aléatoire' WHERE `entry` = 528;
UPDATE `mangos_string` SET `content_loc2` = 'Point de passage' WHERE `entry` = 529;
UPDATE `mangos_string` SET `content_loc2` = 'Animal aléatoire' WHERE `entry` = 530;
UPDATE `mangos_string` SET `content_loc2` = 'Confus' WHERE `entry` = 531;
UPDATE `mangos_string` SET `content_loc2` = 'Ciblé sur le joueur %s (lowguid %u)' WHERE `entry` = 532;
UPDATE `mangos_string` SET `content_loc2` = 'Ciblé sur la créature %s (lowguid %u)' WHERE `entry` = 533;
UPDATE `mangos_string` SET `content_loc2` = 'Ciblé sur <NULL>' WHERE `entry` = 534;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvement domestique à (X: %f Y: %f Z: %f)' WHERE `entry` = 535;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvement domestique utilisé pour le joueur ?!?' WHERE `entry` = 536;
UPDATE `mangos_string` SET `content_loc2` = 'Déplacement de vol' WHERE `entry` = 537;
UPDATE `mangos_string` SET `content_loc2` = 'Générateur de mouvement inconnu (%u)' WHERE `entry` = 538;
UPDATE `mangos_string` SET `content_loc2` = 'PNJ sélectionné\nGUID: %u.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).' WHERE `entry` = 539;
UPDATE `mangos_string` SET `content_loc2` = 'Niveau: %u.' WHERE `entry` = 540;
UPDATE `mangos_string` SET `content_loc2` = 'Vie (base): %u. (max): %u. (actuelle): %u.' WHERE `entry` = 541;
UPDATE `mangos_string` SET `content_loc2` = 'Unit Flags: %u.\nDynamique Flags: %u.\nFaction Template: %u.' WHERE `entry` = 542;
UPDATE `mangos_string` SET `content_loc2` = 'Loot: %u Pickpocket: %u Dépeçage: %u' WHERE `entry` = 543;
UPDATE `mangos_string` SET `content_loc2` = 'Position: %f %f %f.' WHERE `entry` = 544;
UPDATE `mangos_string` SET `content_loc2` = '*** Est un marchand !' WHERE `entry` = 545;
UPDATE `mangos_string` SET `content_loc2` = '*** Est un entraineur !' WHERE `entry` = 546;
UPDATE `mangos_string` SET `content_loc2` = 'InstanceID: %u' WHERE `entry` = 547;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur%s %s (guid: %u) Compte: %s (id: %u) Niveau MJ: %u Dernière IP: %s Dernière connection: %s Latence: %ums' WHERE `entry` = 548;
UPDATE `mangos_string` SET `content_loc2` = 'Temps de jeu: %s Niveau: %u Argent: %ug%us%uc' WHERE `entry` = 549;
UPDATE `mangos_string` SET `content_loc2` = 'Commande .pinfo ne supporte pas l\'option \'rep\' pour les joueurs hors ligne.' WHERE `entry` = 550;
UPDATE `mangos_string` SET `content_loc2` = '%s a désormais exploré toutes les zones.' WHERE `entry` = 551;
UPDATE `mangos_string` SET `content_loc2` = '%s a encore des zones à explorer.' WHERE `entry` = 552;
UPDATE `mangos_string` SET `content_loc2` = '%s a exploré toutes les zones pour vous.' WHERE `entry` = 553;
UPDATE `mangos_string` SET `content_loc2` = '%s a caché toutes les zones pour vous.' WHERE `entry` = 554;
UPDATE `mangos_string` SET `content_loc2` = 'Planer activé' WHERE `entry` = 555;
UPDATE `mangos_string` SET `content_loc2` = 'Planer désactivé' WHERE `entry` = 556;
UPDATE `mangos_string` SET `content_loc2` = '%s augmente votre niveau à (%i).' WHERE `entry` = 557;
UPDATE `mangos_string` SET `content_loc2` = '%s baisse votre niveau à (%i).' WHERE `entry` = 558;
UPDATE `mangos_string` SET `content_loc2` = '%s réinitialise votre niveau de progression.' WHERE `entry` = 559;
UPDATE `mangos_string` SET `content_loc2` = 'Cette zone a été marquée comme explorée.' WHERE `entry` = 560;
UPDATE `mangos_string` SET `content_loc2` = 'Cette zone a été marquée comme non-explorée.' WHERE `entry` = 561;
UPDATE `mangos_string` SET `content_loc2` = 'GUID = %i updateIndex: %i, value: %i.' WHERE `entry` = 562;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez changé la valeur UpdateIndex %i de GUID = %i en %i.' WHERE `entry` = 563;
UPDATE `mangos_string` SET `content_loc2` = 'La valeur index %u est trop grande pour %u (nombre: %u).' WHERE `entry` = 564;
UPDATE `mangos_string` SET `content_loc2` = 'Modification uint32 %u: [OPCODE]: %u [VALEUR]: %u' WHERE `entry` = 565;
UPDATE `mangos_string` SET `content_loc2` = 'Vous modifiez le champ %u: %u en un uint32: %u' WHERE `entry` = 566;
UPDATE `mangos_string` SET `content_loc2` = 'Modification float %u: [OPCODE]: %u [VALEUR]: %f' WHERE `entry` = 567;
UPDATE `mangos_string` SET `content_loc2` = 'Vous modifiez le champ %u: %i en un float: %f' WHERE `entry` = 568;
UPDATE `mangos_string` SET `content_loc2` = 'Récupération uint32 %u: [OPCODE]: %u [VALEUR]: %u' WHERE `entry` = 569;
UPDATE `mangos_string` SET `content_loc2` = 'La valeur uint32 de %u dans %u est: %u' WHERE `entry` = 570;
UPDATE `mangos_string` SET `content_loc2` = 'Récupération float %u: [OPCODE]: %u [VALEUR]: %f' WHERE `entry` = 571;
UPDATE `mangos_string` SET `content_loc2` = 'La valeur float de %u dans %u est: %f' WHERE `entry` = 572;
UPDATE `mangos_string` SET `content_loc2` = '.Mod32Value: [OPCODE]: %u [VALEUR]: %i' WHERE `entry` = 575;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez modifié la valeur du champ: %u à la valeur: %u' WHERE `entry` = 576;
UPDATE `mangos_string` SET `content_loc2` = 'Vous êtes maintenant invisible.' WHERE `entry` = 577;
UPDATE `mangos_string` SET `content_loc2` = 'Vous êtes maintenant visible.' WHERE `entry` = 578;
UPDATE `mangos_string` SET `content_loc2` = 'Sélectionnez un joueur ou une créature non ennemi.' WHERE `entry` = 579;
UPDATE `mangos_string` SET `content_loc2` = 'Le joueur %s a appris tous les sorts de race/classe par défaut et a complété toutes les quêtes récompensant des sorts.' WHERE `entry` = 580;
UPDATE `mangos_string` SET `content_loc2` = 'Objets trouvés à proximité (distance %f): %u' WHERE `entry` = 581;
UPDATE `mangos_string` SET `content_loc2` = 'Temps avant réapparition: Complet: %s Restant: %s' WHERE `entry` = 582;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE `entry` = 583;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun event trouvé !' WHERE `entry` = 584;
UPDATE `mangos_string` SET `content_loc2` = 'Event inexistant !' WHERE `entry` = 585;
UPDATE `mangos_string` SET `content_loc2` = 'Event %u: %s%s\nDebut: %s Fin: %s Occurence: %s Durée: %s\nProchain changement de phase: %s' WHERE `entry` = 586;
UPDATE `mangos_string` SET `content_loc2` = 'Event %u déjà actif !' WHERE `entry` = 587;
UPDATE `mangos_string` SET `content_loc2` = 'Event %u inactif !' WHERE `entry` = 588;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvement ponctuel (X: %f Y: %f Z: %f)' WHERE `entry` = 589;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvement de peur' WHERE `entry` = 590;
UPDATE `mangos_string` SET `content_loc2` = 'Mouvement de distraction' WHERE `entry` = 591;
UPDATE `mangos_string` SET `content_loc2` = 'Vous avez appris toutes les recettes de métiers: %s' WHERE `entry` = 592;
UPDATE `mangos_string` SET `content_loc2` = 'Comptes actuellement bannis:' WHERE `entry` = 593;
UPDATE `mangos_string` SET `content_loc2` = '|    Compte     |   DateBan    |   DateDeban  |   Banni par   |    Raison     |' WHERE `entry` = 594;
UPDATE `mangos_string` SET `content_loc2` = 'IP actuellement bannies:' WHERE `entry` = 595;
UPDATE `mangos_string` SET `content_loc2` = '|      IP       |   DateBan    |   DateDeban  |   Banni par   |    Raison     |' WHERE `entry` = 596;
UPDATE `mangos_string` SET `content_loc2` = 'Maîtres-du-jeu actuels:' WHERE `entry` = 597;
UPDATE `mangos_string` SET `content_loc2` = '|    Compte     |  MJ  |' WHERE `entry` = 598;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun Maître-du-jeu.' WHERE `entry` = 599;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance gagne !' WHERE `entry` = 600;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde gagne !' WHERE `entry` = 601;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour le goulet des Chanteguerres commence dans 1 minute.' WHERE `entry` = 602;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour le goulet des Chanteguerres commence dans 30 secondes. Préparez-vous !' WHERE `entry` = 603;
UPDATE `mangos_string` SET `content_loc2` = 'Que la bataille pour le goulet des Chanteguerres commence !' WHERE `entry` = 604;
UPDATE `mangos_string` SET `content_loc2` = '$N a capturé le drapeau de la Horde !' WHERE `entry` = 605;
UPDATE `mangos_string` SET `content_loc2` = '$N a capturé le drapeau de l\'Alliance !' WHERE `entry` = 606;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de la Horde a été laché par $N!' WHERE `entry` = 607;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de l\'Alliance a été laché par $N !' WHERE `entry` = 608;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de l\'Alliance a été ramené à sa base par $N !' WHERE `entry` = 609;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de la Horde a été ramené à sa base par $N !' WHERE `entry` = 610;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de la Horde a été ramassé par $N !' WHERE `entry` = 611;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de l\'Alliance a été ramassé par $N !' WHERE `entry` = 612;
UPDATE `mangos_string` SET `content_loc2` = 'Les drapeaux sont maintenant placés sur leur base.' WHERE `entry` = 613;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de l\'Alliance est maintenant placé sur sa base.' WHERE `entry` = 614;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de la Horde est maintenant placé sur sa base.' WHERE `entry` = 615;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour l\'Oeil du Cyclone débute dans 1 minute.' WHERE `entry` = 636;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour l\'Oeil du Cyclone débute dans 30 secondes. Préparez-vous !' WHERE `entry` = 637;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour l\'Oeil du Cyclone débute !' WHERE `entry` = 638;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance' WHERE `entry` = 650;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde' WHERE `entry` = 651;
UPDATE `mangos_string` SET `content_loc2` = 'les Écuries' WHERE `entry` = 652;
UPDATE `mangos_string` SET `content_loc2` = 'la Forge' WHERE `entry` = 653;
UPDATE `mangos_string` SET `content_loc2` = 'la Ferme' WHERE `entry` = 654;
UPDATE `mangos_string` SET `content_loc2` = 'la Scierie' WHERE `entry` = 655;
UPDATE `mangos_string` SET `content_loc2` = 'la Mine' WHERE `entry` = 656;
UPDATE `mangos_string` SET `content_loc2` = '%s a pris %s.' WHERE `entry` = 657;
UPDATE `mangos_string` SET `content_loc2` = '$N a défendu %s.' WHERE `entry` = 658;
UPDATE `mangos_string` SET `content_loc2` = '$N a attaqué %s.' WHERE `entry` = 659;
UPDATE `mangos_string` SET `content_loc2` = '$N a pris %s ! Si personne n\'intervient, %s s\'en emparera dans 1 minute !' WHERE `entry` = 660;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour le Bassin d\'Arathi commence dans une minute.' WHERE `entry` = 661;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour le Bassin d\'Arathi commence dans 30 secondes. Préparez-vous !' WHERE `entry` = 662;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour le Bassin d\'Arathi commence !' WHERE `entry` = 663;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a réunie $1776W unités de ressources, et est proche de la victoire !' WHERE `entry` = 664;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a réunie $1777W unités de ressources, et est proche de la victoire !' WHERE `entry` = 665;
UPDATE `mangos_string` SET `content_loc2` = 'Suite à votre récente bataille dans %s, nous avons tenté de vous récompenser avec une marque d’honneur, mais sans succès. Vous trouverez ci-joint la marque d’honneur que nous n’avons pas pu vous remettre sur le moment. Merci d’avoir combattu dans %s !' WHERE `entry` = 666;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle de la Tour des mages !' WHERE `entry` = 667;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle de la Tour des mages !' WHERE `entry` = 668;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle des Ruines draeneï !' WHERE `entry` = 669;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle des Ruines draeneï !' WHERE `entry` = 670;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle de la Tour des elfes de sang !' WHERE `entry` = 671;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle de la Tour des elfes de sang !' WHERE `entry` = 672;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle des Ruines des saccageurs gangrenés !' WHERE `entry` = 673;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle des Ruines des saccageurs gangrenés !' WHERE `entry` = 674;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle de la Tour des mages !' WHERE `entry` = 675;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle de la Tour des mages !' WHERE `entry` = 676;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle des Ruines draeneï !' WHERE `entry` = 677;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle des Ruines draeneï !' WHERE `entry` = 678;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle de la Tour des elfes de sang !' WHERE `entry` = 679;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle de la Tour des elfes de sang !' WHERE `entry` = 680;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle des Ruines des saccageurs gangrenés !' WHERE `entry` = 681;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle des Ruines des saccageurs gangrenés !' WHERE `entry` = 682;
UPDATE `mangos_string` SET `content_loc2` = '%s a perdu le drapeau !' WHERE `entry` = 683;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a capturé le drapeau !' WHERE `entry` = 684;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a capturé le drapeau !' WHERE `entry` = 685;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau a été laché.' WHERE `entry` = 686;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau a été réinitialisé.' WHERE `entry` = 687;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez être niveau %u pour former une équipe d\'arène.' WHERE `entry` = 700;
UPDATE `mangos_string` SET `content_loc2` = 'L\'arène ouvre ses portes dans une minute !' WHERE `entry` = 701;
UPDATE `mangos_string` SET `content_loc2` = 'L\'arène ouvre ses portes dans 30 secondes !' WHERE `entry` = 702;
UPDATE `mangos_string` SET `content_loc2` = 'L\'arène ouvre ses portes dans 15 secondes !' WHERE `entry` = 703;
UPDATE `mangos_string` SET `content_loc2` = 'Le match a débuté !' WHERE `entry` = 704;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez attendre %s avant de retrouver la parole.' WHERE `entry` = 705;
UPDATE `mangos_string` SET `content_loc2` = 'Les équipements suivant ont des problèmes avec leur stockage dans l\'inventaire.' WHERE `entry` = 706;
UPDATE `mangos_string` SET `content_loc2` = '%s ne souhaite pas être dérangé et ne peut pas recevoir de chuchotements: %s' WHERE `entry` = 707;
UPDATE `mangos_string` SET `content_loc2` = '%s est absent: %s' WHERE `entry` = 708;
UPDATE `mangos_string` SET `content_loc2` = 'Ne pas déranger' WHERE `entry` = 709;
UPDATE `mangos_string` SET `content_loc2` = 'Absent' WHERE `entry` = 710;
UPDATE `mangos_string` SET `content_loc2` = 'Statut de la file d\'attente pour %s (Lvl: %u à %u)\nFile d\'attente de l\'Alliance: %u (requiert encore %u)\nFile d\'attente de la Horde: %u (requiert encore %u)' WHERE `entry` = 711;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Annonce File d\'attente CB]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE `entry` = 712;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez être niveau %u pour rejoindre une équipe d\'arène !' WHERE `entry` = 713;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne remplissez pas les exigences de niveau de ce champ de bataille.' WHERE `entry` = 715;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Annonce File d\'attente CB]:|r %s -- [%u-%u] Cela débute !|r' WHERE `entry` = 717;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Annonce file d\'attente d\'Arène]:|r Toutes les arènes -- Entrée : %ux%u : %u|r' WHERE `entry` = 718;
UPDATE `mangos_string` SET `content_loc2` = '|cffff0000[Annonce file d\'attente d\'Arène]:|r Toutes les arènes -- Sortie : %ux%u : %u|r' WHERE `entry` = 719;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe est trop grand pour ce champ de bataille. Veuillez regrouper pour rejoindre.' WHERE `entry` = 720;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe est trop grand pour cette arène. Veuillez regrouper pour rejoindre.' WHERE `entry` = 721;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte des membres n\'appartenant pas à votre équipe d\'arène. Veuillez regrouper pour rejoindre.' WHERE `entry` = 722;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe ne comporte pas assez de joueurs pour rejoindre ce match.' WHERE `entry` = 723;
UPDATE `mangos_string` SET `content_loc2` = 'L\'équipe d\'Or l\'emporte !' WHERE `entry` = 724;
UPDATE `mangos_string` SET `content_loc2` = 'L\'équipe Verte l\'emporte !' WHERE `entry` = 725;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a pas assez de joueurs sur ce champ de bataille. Il prendra bientôt fin, à moins que des joueurs le rejoigne afin d\'équilibrer la balance.' WHERE `entry` = 726;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte un membre hors ligne. Veuillez le supprimer avant de rejoindre.' WHERE `entry` = 727;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe contient des joueurs d\'une faction opposée. Vous ne pouvez pas rejoindre ce champ de bataille comme un groupe.' WHERE `entry` = 728;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte des joueurs de différentes tranches de niveau. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 729;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est déjà inscrit pour ce champ de bataille. Il doit le quitter avant que vous puissiez rejoindre ce champ de bataille comme un groupe.' WHERE `entry` = 730;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est un déserteur. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 731;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est déjà inscrit pour trois champ de bataille. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 732;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas téléporter sur une carte de champ de bataille ou d\'arène.' WHERE `entry` = 733;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas invoquer un joueur sur une carte de champ de bataille ou d\'arène.' WHERE `entry` = 734;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez être en mode MJ afin de téléporter un joueur dans sur un champ de bataille.' WHERE `entry` = 735;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas vous téléporter d\'un champ de bataille à un autre. Veuillez d\'abord quitter le champ de bataille actuel.' WHERE `entry` = 736;
UPDATE `mangos_string` SET `content_loc2` = 'Les arènes sont configurées en mode 1c1 pour débogage. Vous ne pouvez donc pas rejoindre comme un groupe.' WHERE `entry` = 737;
UPDATE `mangos_string` SET `content_loc2` = 'Les arènes sont configurées avec le quota normal de joueurs.' WHERE `entry` = 738;
UPDATE `mangos_string` SET `content_loc2` = 'Les champs de bataille sont configurés en mode 1c0 pour débogage.' WHERE `entry` = 739;
UPDATE `mangos_string` SET `content_loc2` = 'Les champs de bataille sont configurés avec le quota normal de joueurs.' WHERE `entry` = 740;
UPDATE `mangos_string` SET `content_loc2` = 'Mise à jour des points d\'arène en fonction des statistiques des équipes. Cela peut prendre plusieurs minutes. Veuillez patienter...' WHERE `entry` = 741;
UPDATE `mangos_string` SET `content_loc2` = 'Distribution des points d\'arènes aux joueurs...' WHERE `entry` = 742;
UPDATE `mangos_string` SET `content_loc2` = 'Fin de configuration des points d\'arène pour les joueurs connectés.' WHERE `entry` = 743;
UPDATE `mangos_string` SET `content_loc2` = 'Modification du quota de joueurs, des points d\'arène etc. pour les équipes d\'arène chargées. Envoi des nouvelles statistiques aux joueurs connectés...' WHERE `entry` = 744;
UPDATE `mangos_string` SET `content_loc2` = 'Modification effectuée.' WHERE `entry` = 745;
UPDATE `mangos_string` SET `content_loc2` = 'Mise à jour des points d\'arène effectuée.' WHERE `entry` = 746;
UPDATE `mangos_string` SET `content_loc2` = 'Pas assez de joueurs. Le jeu se termine dans %u min.' WHERE `entry` = 750;
UPDATE `mangos_string` SET `content_loc2` = 'Pas assez de joueurs. Le jeu se termine dans %u sec.' WHERE `entry` = 751;
UPDATE `mangos_string` SET `content_loc2` = 'Seule l\'Alliance peut emprunter ce portail.' WHERE `entry` = 752;
UPDATE `mangos_string` SET `content_loc2` = 'Seule la Horde peut emprunter ce portail.' WHERE `entry` = 753;
UPDATE `mangos_string` SET `content_loc2` = '%s a été détruit par %s !' WHERE `entry` = 759;
UPDATE `mangos_string` SET `content_loc2` = '%s est attaqué ! Si personne n\'intervient, %s va le détruire !' WHERE `entry` = 760;
UPDATE `mangos_string` SET `content_loc2` = '%s a été pris par %s !' WHERE `entry` = 761;
UPDATE `mangos_string` SET `content_loc2` = '%s a été pris par %s !' WHERE `entry` = 762;
UPDATE `mangos_string` SET `content_loc2` = '%s a été pris par %s !' WHERE `entry` = 763;
UPDATE `mangos_string` SET `content_loc2` = '%s est attaqué ! Si personne n\'intervient, %s va s’en emparer !' WHERE `entry` = 764;
UPDATE `mangos_string` SET `content_loc2` = '%s s\'est emparée de %s ! Ses fournitures vont permettre d\'équiper des renforts !' WHERE `entry` = 765;
UPDATE `mangos_string` SET `content_loc2` = 'la mine de Gouffrefer' WHERE `entry` = 766;
UPDATE `mangos_string` SET `content_loc2` = 'la mine de Froide-dent' WHERE `entry` = 767;
UPDATE `mangos_string` SET `content_loc2` = 'Le poste de secours Foudrepique' WHERE `entry` = 768;
UPDATE `mangos_string` SET `content_loc2` = 'Le fortin sud de Dun Baldar' WHERE `entry` = 769;
UPDATE `mangos_string` SET `content_loc2` = 'Le fortin nord de Dun Baldar' WHERE `entry` = 770;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière Foudrepique' WHERE `entry` = 771;
UPDATE `mangos_string` SET `content_loc2` = 'Le fortin de l\'Aile de glace' WHERE `entry` = 772;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière de Gîtepierre' WHERE `entry` = 773;
UPDATE `mangos_string` SET `content_loc2` = 'Le fortin de Gîtepierre' WHERE `entry` = 774;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière des neiges' WHERE `entry` = 775;
UPDATE `mangos_string` SET `content_loc2` = 'La tour de Glace-sang' WHERE `entry` = 776;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière de Glace-sang' WHERE `entry` = 777;
UPDATE `mangos_string` SET `content_loc2` = 'La Tour de la halte' WHERE `entry` = 778;
UPDATE `mangos_string` SET `content_loc2` = 'Le cimetière Loup-de-givre' WHERE `entry` = 779;
UPDATE `mangos_string` SET `content_loc2` = 'La tour Loup-de-givre orientale' WHERE `entry` = 780;
UPDATE `mangos_string` SET `content_loc2` = 'La tour Loup-de-givre occidentale' WHERE `entry` = 781;
UPDATE `mangos_string` SET `content_loc2` = 'La hutte de guérison Loup-de-givre' WHERE `entry` = 782;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour la Vallée d\'Alterac commence dans 1 minute.' WHERE `entry` = 784;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour la Vallée d\'Alterac commence dans 30 secondes. Préparez-vous !' WHERE `entry` = 785;
UPDATE `mangos_string` SET `content_loc2` = 'La bataille pour la Vallée d\'Alterac commence !' WHERE `entry` = 786;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance sera bientôt à court de renforts !' WHERE `entry` = 787;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde sera bientôt à court de renforts !' WHERE `entry` = 788;
UPDATE `mangos_string` SET `content_loc2` = 'Le général Loup-de-givre est mort !' WHERE `entry` = 789;
UPDATE `mangos_string` SET `content_loc2` = 'Le général Foudrepique est mort !' WHERE `entry` = 790;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne possédez pas assez d\'argent' WHERE `entry` = 801;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne possédez pas assez d\'emplacements libres dans votre inventaire' WHERE `entry` = 802;
UPDATE `mangos_string` SET `content_loc2` = 'Votre partenaire ne possède pas assez d\'emplacements libres dans son inventaire' WHERE `entry` = 803;
UPDATE `mangos_string` SET `content_loc2` = 'Vous n\'avez pas la permission d\'exécuter cette fonction' WHERE `entry` = 804;
UPDATE `mangos_string` SET `content_loc2` = 'Langue inconnue' WHERE `entry` = 805;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne connaissez pas cette langue' WHERE `entry` = 806;
UPDATE `mangos_string` SET `content_loc2` = 'Veuillez fournir un nom de personnage' WHERE `entry` = 807;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur %s introuvable ou hors ligne' WHERE `entry` = 808;
UPDATE `mangos_string` SET `content_loc2` = 'Compte du personnage %s introuvable' WHERE `entry` = 809;
UPDATE `mangos_string` SET `content_loc2` = '|Hplayer:$N|h[$N]|h a accompli le haut fait $a !' WHERE `entry` = 810;
UPDATE `mangos_string` SET `content_loc2` = 'Maître de guilde' WHERE `entry` = 811;
UPDATE `mangos_string` SET `content_loc2` = 'Officier' WHERE `entry` = 812;
UPDATE `mangos_string` SET `content_loc2` = 'Vétéran' WHERE `entry` = 813;
UPDATE `mangos_string` SET `content_loc2` = 'Membre' WHERE `entry` = 814;
UPDATE `mangos_string` SET `content_loc2` = 'Initié' WHERE `entry` = 815;
UPDATE `mangos_string` SET `content_loc2` = 'Arrêt du démon...' WHERE `entry` = 1000;
UPDATE `mangos_string` SET `content_loc2` = 'Compte supprimé: %s' WHERE `entry` = 1001;
UPDATE `mangos_string` SET `content_loc2` = 'Compte %s NON supprimé (le format du fichier SQL a probablement été mis à jour).' WHERE `entry` = 1002;
UPDATE `mangos_string` SET `content_loc2` = 'Compte %s NON supprimé (erreur inconnue)' WHERE `entry` = 1003;
UPDATE `mangos_string` SET `content_loc2` = 'Compte créé: %s' WHERE `entry` = 1004;
UPDATE `mangos_string` SET `content_loc2` = 'Le nom de compte ne peut pas dépasser 16 caractères (limite du client). Compte NON créé !' WHERE `entry` = 1005;
UPDATE `mangos_string` SET `content_loc2` = 'Ce nom de compte existe déjà !' WHERE `entry` = 1006;
UPDATE `mangos_string` SET `content_loc2` = 'Compte %s NON créé (le format du fichier SQL a probablement été mis à jour)' WHERE `entry` = 1007;
UPDATE `mangos_string` SET `content_loc2` = 'Compte %s NON créé (erreur inconnue)' WHERE `entry` = 1008;
UPDATE `mangos_string` SET `content_loc2` = 'Joueur %s (Guid: %u) du compte %s (Id: %u) supprimé.' WHERE `entry` = 1009;
UPDATE `mangos_string` SET `content_loc2` = '|     Compte    |      Personnage      |       IP        | MJ | Extension |' WHERE `entry` = 1010;
UPDATE `mangos_string` SET `content_loc2` = '|<Erreur>       | %20s |<Erreur>         |<Er>| <Erreur>  |' WHERE `entry` = 1011;
UPDATE `mangos_string` SET `content_loc2` = ' =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = ' WHERE `entry` = 1012;
UPDATE `mangos_string` SET `content_loc2` = '|%15s| %20s | %15s |%4d| %9d |' WHERE `entry` = 1013;
UPDATE `mangos_string` SET `content_loc2` = 'Aucun joueur en ligne.' WHERE `entry` = 1014;
UPDATE `mangos_string` SET `content_loc2` = 'Commande invalide ou incomplète. Tapez quit pour fermer la session.' WHERE `entry` = 1015;
UPDATE `mangos_string` SET `content_loc2` = 'Compte %s (Id: %u) a désormais la permission d\'utiliser l\'expansion %u.' WHERE `entry` = 1100;
UPDATE `mangos_string` SET `content_loc2` = 'Message du jour changé en:\n%s' WHERE `entry` = 1101;
UPDATE `mangos_string` SET `content_loc2` = 'Message envoyé à %s: %s' WHERE `entry` = 1102;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s %s' WHERE `entry` = 1103;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s' WHERE `entry` = 1104;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s' WHERE `entry` = 1105;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s %s' WHERE `entry` = 1106;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s' WHERE `entry` = 1107;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s %s' WHERE `entry` = 1108;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s %s %s %s' WHERE `entry` = 1109;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s X: %f Y: %f Z: %f MapId: %d' WHERE `entry` = 1110;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s X: %f Y: %f Z: %f MapId: %d' WHERE `entry` = 1111;
UPDATE `mangos_string` SET `content_loc2` = 'Erreur lors de l\'ouverture du fichier: %s' WHERE `entry` = 1112;
UPDATE `mangos_string` SET `content_loc2` = 'Le compte %s (%u) a atteint la limite de personnages autorisés (limite du client)' WHERE `entry` = 1113;
UPDATE `mangos_string` SET `content_loc2` = 'Le fichier exporté comporte des champs défaillants !' WHERE `entry` = 1114;
UPDATE `mangos_string` SET `content_loc2` = 'Nom de personnage invalide !' WHERE `entry` = 1115;
UPDATE `mangos_string` SET `content_loc2` = 'GUID de personnage invalide !' WHERE `entry` = 1116;
UPDATE `mangos_string` SET `content_loc2` = 'Personnage de GUID %u en action !' WHERE `entry` = 1117;
UPDATE `mangos_string` SET `content_loc2` = '%d - guilde: %s (guid: %u) %s' WHERE `entry` = 1118;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez utiliser male ou female comme sexe.' WHERE `entry` = 1119;
UPDATE `mangos_string` SET `content_loc2` = 'Vous changez le sexe de %s en %s.' WHERE `entry` = 1120;
UPDATE `mangos_string` SET `content_loc2` = 'Votre sexe a été changé en %s par %s.' WHERE `entry` = 1121;
UPDATE `mangos_string` SET `content_loc2` = '(%u/%u +perm %u +temp %u)' WHERE `entry` = 1122;
UPDATE `mangos_string` SET `content_loc2` = 'Familier introuvable.' WHERE `entry` = 1123;
UPDATE `mangos_string` SET `content_loc2` = 'Type de familier invalide.' WHERE `entry` = 1124;
UPDATE `mangos_string` SET `content_loc2` = 'Votre familier a appris tous ses talents.' WHERE `entry` = 1125;
UPDATE `mangos_string` SET `content_loc2` = 'Les talents de votre familier ont été réinitialisés.' WHERE `entry` = 1126;
UPDATE `mangos_string` SET `content_loc2` = 'Les talents du familier de %s ont été réinitialisés.' WHERE `entry` = 1127;
UPDATE `mangos_string` SET `content_loc2` = '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Carte:%u X:%f Y:%f Z:%f)' WHERE `entry` = 1128;
UPDATE `mangos_string` SET `content_loc2` = '%d - %s %s (Carte:%u X:%f Y:%f Z:%f)' WHERE `entry` = 1129;
UPDATE `mangos_string` SET `content_loc2` = 'L\'événement %u "%s" a débuté.' WHERE `entry` = 1130;
UPDATE `mangos_string` SET `content_loc2` = 'L\'événement %u "%s" s\'est terminé.' WHERE `entry` = 1131;
UPDATE `mangos_string` SET `content_loc2` = 'Vous essayez de visionner une cinématique inexistante.' WHERE `entry` = 1200;
UPDATE `mangos_string` SET `content_loc2` = 'Vous essayez de visionner une vidéo inexistante.' WHERE `entry` = 1201;
