SET NAMES utf8;

UPDATE `areatrigger_tavern` SET `name` = 'Marche de L\'ouest - Auberge de la Colline des Sentinelles' WHERE id = 71;
UPDATE `areatrigger_tavern` SET `name` = 'Forêt d\'Elwynn - Compté-de-l\'or - Auberge de la Fierté du Lion' WHERE id = 562;
UPDATE `areatrigger_tavern` SET `name` = 'Canyons des Carmines - Auberge de Compté-du-lac' WHERE id = 682;
UPDATE `areatrigger_tavern` SET `name` = 'Bois de la Pénombre - Sombre-comté - Taverne du Corbeau écarlate' WHERE id = 707;
UPDATE `areatrigger_tavern` SET `name` = 'Contreforts de Hautebrande - Auberge d\'Austrivage' WHERE id = 708;
UPDATE `areatrigger_tavern` SET `name` = 'Marécage d\'âprefange - île de Theramore' WHERE id = 709;
UPDATE `areatrigger_tavern` SET `name` = 'Dun Morogh - Kharanos - Distillerie Tonnebière' WHERE id = 710;
UPDATE `areatrigger_tavern` SET `name` = 'Loch Modan - Thelsamar - Auberge de la Fortebière' WHERE id = 712;
UPDATE `areatrigger_tavern` SET `name` = 'Les Paluns - Baie de Menethil - Taverne de l\'Eau profonde' WHERE id = 713;
UPDATE `areatrigger_tavern` SET `name` = 'Teldrassil - Dolanaar' WHERE id = 715;
UPDATE `areatrigger_tavern` SET `name` = 'Sombrivage - Auberdine' WHERE id = 716;
UPDATE `areatrigger_tavern` SET `name` = 'Orneval - Astranaar' WHERE id = 717;
UPDATE `areatrigger_tavern` SET `name` = 'Forêt des Pins argentés' WHERE id = 720;
UPDATE `areatrigger_tavern` SET `name` = 'Contreforts de Hautebrande' WHERE id = 721;
UPDATE `areatrigger_tavern` SET `name` = 'Mulgore' WHERE id = 722;
UPDATE `areatrigger_tavern` SET `name` = 'Les Carmines' WHERE id = 742;
UPDATE `areatrigger_tavern` SET `name` = 'Les Carmines' WHERE id = 743;
UPDATE `areatrigger_tavern` SET `name` = 'Durotar' WHERE id = 843;
UPDATE `areatrigger_tavern` SET `name` = 'Marais des Chagrins' WHERE id = 844;
UPDATE `areatrigger_tavern` SET `name` = 'Vallée de Strangleronce' WHERE id = 862;
UPDATE `areatrigger_tavern` SET `name` = 'Les Carmines' WHERE id = 982;
UPDATE `areatrigger_tavern` SET `name` = 'Les Serres-Rocheuses' WHERE id = 1022;
UPDATE `areatrigger_tavern` SET `name` = 'Tanaris' WHERE id = 1023;
UPDATE `areatrigger_tavern` SET `name` = 'Féralas' WHERE id = 1024;
UPDATE `areatrigger_tavern` SET `name` = 'Féralas' WHERE id = 1025;
UPDATE `areatrigger_tavern` SET `name` = 'Terres ingrates' WHERE id = 1606;
UPDATE `areatrigger_tavern` SET `name` = 'Hautes-terres d\'Arathi' WHERE id = 1646;
UPDATE `areatrigger_tavern` SET `name` = 'Désolace' WHERE id = 2266;
UPDATE `areatrigger_tavern` SET `name` = 'Désolace' WHERE id = 2267;
UPDATE `areatrigger_tavern` SET `name` = 'Mille pointes' WHERE id = 2286;
UPDATE `areatrigger_tavern` SET `name` = 'Berceau-de-l\'Hiver' WHERE id = 2287;
UPDATE `areatrigger_tavern` SET `name` = 'Orneval' WHERE id = 2610;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne de l\'Île de sang maudit' WHERE id = 2746;
UPDATE `areatrigger_tavern` SET `name` = 'Campement Grom\'Gol' WHERE id = 3886;
UPDATE `areatrigger_tavern` SET `name` = 'La chapelle de l\'Espoir de Lumière' WHERE id = 4058;
UPDATE `areatrigger_tavern` SET `name` = 'Enclave cénarienne' WHERE id = 3985;
UPDATE `areatrigger_tavern` SET `name` = 'Pic des Serres-Rocheuses' WHERE id = 4090;
UPDATE `areatrigger_tavern` SET `name` = 'Auberge du Guet d\'azur' WHERE id = 4240;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne de la Place de l\'Epervier' WHERE id = 4486;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne du Bastion de l\'Honneur' WHERE id = 4337;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne de Thrallmar' WHERE id = 4336;
UPDATE `areatrigger_tavern` SET `name` = 'Refuge cénarien' WHERE id = 4382;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne de Zabra\'jin' WHERE id = 4373;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne du Village de Sombrelune' WHERE id = 4526;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne du Bastion des Marteaux-Hardis' WHERE id = 4528;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne du Sanctum des étoiles' WHERE id = 4607;
UPDATE `areatrigger_tavern` SET `name` = 'Strahnbrande' WHERE id = 178;
UPDATE `areatrigger_tavern` SET `name` = 'Taverne de Telredor' WHERE id = 4374;
UPDATE `areatrigger_tavern` SET `name` = 'Village des Vengebroches' WHERE id = 3690;
