SET NAMES utf8;

UPDATE `gossip_texts` SET `content_loc2` = '[PH] SD2 texte inconnu' WHERE `entry` = -3000000;
UPDATE `gossip_texts` SET `content_loc2` = 'Taruk m\'envoi pour recueillir ce que vous devez.' WHERE `entry` = -3000101;
UPDATE `gossip_texts` SET `content_loc2` = 'Payez, Harry !' WHERE `entry` = -3000102;
UPDATE `gossip_texts` SET `content_loc2` = 'Je suis prêt à voyager jusqu\'à votre village.' WHERE `entry` = -3000103;
UPDATE `gossip_texts` SET `content_loc2` = '<Verifie le pouls...>' WHERE `entry` = -3000104;
UPDATE `gossip_texts` SET `content_loc2` = 'Ezéchiel dit que vous pourriez avoir un certain livre ...' WHERE `entry` = -3000105;
UPDATE `gossip_texts` SET `content_loc2` = 'Montrez moi où je peux voler' WHERE `entry` = -3000106;
UPDATE `gossip_texts` SET `content_loc2` = '[PH] Obtenir des bombes de présicion' WHERE `entry` = -3000107;
UPDATE `gossip_texts` SET `content_loc2` = '[PH] Commencer la mission de bombardement' WHERE `entry` = -3000108;
UPDATE `gossip_texts` SET `content_loc2` = 'Que l\'évenement commence !' WHERE `entry` = -3043000;
UPDATE `gossip_texts` SET `content_loc2` = 'Je suis prêt à démarrer !' WHERE `entry` = -3090000;
UPDATE `gossip_texts` SET `content_loc2` = 'Dites-moi davantage.' WHERE `entry` = -3409000;
UPDATE `gossip_texts` SET `content_loc2` = 'Quoi d\'autre avez-vous à dire?' WHERE `entry` = -3409001;
UPDATE `gossip_texts` SET `content_loc2` = 'Vous nous avez défiés et nous sommes venus. Mais où est donc ce maitre dont vous parlez ?' WHERE `entry` = -3409002;
UPDATE `gossip_texts` SET `content_loc2` = 'Je n\'ai pas fait d\'erreur.' WHERE `entry` = -3469000;
UPDATE `gossip_texts` SET `content_loc2` = 'Vous avez perdu l\'esprit, Nefarius. Vous parlez par énigmes.' WHERE `entry` = -3469001;
UPDATE `gossip_texts` SET `content_loc2` = 'Faites donc.' WHERE `entry` = -3469002;
UPDATE `gossip_texts` SET `content_loc2` = 'Je ne peux pas, Vaelastrasz ! Il y a sûrement un moyen de vous guérir !' WHERE `entry` = -3469003;
UPDATE `gossip_texts` SET `content_loc2` = 'Vaelastrasz, non!!!' WHERE `entry` = -3469004;
UPDATE `gossip_texts` SET `content_loc2` = 'Je suis prêt à partir pour le Donjon de Fort-de-Durn' WHERE `entry` = -3560000;
UPDATE `gossip_texts` SET `content_loc2` = 'J\'ai besoin d\'un lot de bombes incendiaires.' WHERE `entry` = -3560001;
UPDATE `gossip_texts` SET `content_loc2` = 'Taretha ne peut vous voir, Thrall.' WHERE `entry` = -3560002;
UPDATE `gossip_texts` SET `content_loc2` = 'La situation est assez compliquée, Thrall. Il serait préférable pour vous que vous preniez la tête des montagnes maintenant, avant que d\'autres hommes de Landenoire ne se manifestent. Nous ferons en sorte de mettre Taretha en lieu sûr.' WHERE `entry` = -3560003;
UPDATE `gossip_texts` SET `content_loc2` = 'Nous sommes prêt, Thrall.' WHERE `entry` = -3560004;
UPDATE `gossip_texts` SET `content_loc2` = 'Etrange sorcier ?' WHERE `entry` = -3560005;
UPDATE `gossip_texts` SET `content_loc2` = 'Nous allons vous sortir de là. Taretha. Ne vous inquiétez pas. Je doute que le magicien ne soit trop loin.' WHERE `entry` = -3560006;
UPDATE `gossip_texts` SET `content_loc2` = 'Que pensez-vous qu\'ils font maintenant?' WHERE `entry` = -3595000;
UPDATE `gossip_texts` SET `content_loc2` = 'Que voulez vous que je fasse ?' WHERE `entry` = -3595001;
UPDATE `gossip_texts` SET `content_loc2` = 'Très bien, Chromie.' WHERE `entry` = -3595002;
UPDATE `gossip_texts` SET `content_loc2` = 'Pourquoi ai-je été renvoyé dans ce lieu et à cette époque précise ?' WHERE `entry` = -3595003;
UPDATE `gossip_texts` SET `content_loc2` = 'Quelle était cette décision?' WHERE `entry` = -3595004;
UPDATE `gossip_texts` SET `content_loc2` = 'Alors, comment le Vol Draconnique projette d\'intervenir ?' WHERE `entry` = -3595005;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers le camp de base de l\'expédition.' WHERE `entry` = -3603000;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers le Champ d\'entraînement.' WHERE `entry` = -3603001;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers la forge colossalle.' WHERE `entry` = -3603002;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers la Ferraillerie.' WHERE `entry` = -3603003;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers l\'antichambre d\'Ulduar' WHERE `entry` = -3603004;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers le passage Brisé.' WHERE `entry` = -3603005;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers le Conservatoire de vie.' WHERE `entry` = -3603006;
UPDATE `gossip_texts` SET `content_loc2` = 'Téleportation vers l\'Étincelle d\'imagination.' WHERE `entry` = -3603007;
UPDATE `gossip_texts` SET `content_loc2` = 'Téléportation vers la Prison de Yogg-Saron' WHERE `entry` = -3603008;
UPDATE `gossip_texts` SET `content_loc2` = 'Activez les cristaux quand nous serons en difficulté, compris ?' WHERE `entry` = -3608000;
UPDATE `gossip_texts` SET `content_loc2` = 'Mettez votre peuple en lieu sur, nous allons maintenir les forces du Vol Draconique Bleu à distance.' WHERE `entry` = -3608001;
UPDATE `gossip_texts` SET `content_loc2` = 'Oui. Nous sommes prêts à relever les défis qui nous attendent.' WHERE `entry` = -3649000;
UPDATE `gossip_texts` SET `content_loc2` = ' S\'il vous plaît déverrouillez la porte de la cour.' WHERE `entry` = -3033000;
